lbl-srg/modelica-buildings

Buildings/Fluid/Movers/BaseClasses/PartialFlowMachine.mo
This is for #346 if you agree to the issue.
I did not add a final modifier since the other parameters did not have this either. I did not run the unit tests or added a revision change since this change is very minor.
=> Issue 346 propagated m_flow_small in PartialFlowMachine.mo

Buildings/Fluid/SolarCollectors/BaseClasses/PartialSolarCollector.mo
This is for #357 
did not check unit tests
=> issue 357 propagation of parameters in PartialSolarCollector.mo

Buildings/Fluid/Movers/BaseClasses/ControlledFlowMachine.mo, Buildings/Fluid/Movers/SpeedControlled_y.mo
This is for issue #360 
I reran unit tests for the movers package only since I was unable to successfully complete the entire batch of unit tests.
=> Issue 360 : made per records replaceable in movers

Buildings/Fluid/Interfaces/ConservationEquation.mo
All unit tests produce the same result.
This closes #371
=> Merged from Annex60, branch issue170_massDynamics

Buildings/Fluid/Storage/BaseClasses/IndirectTankHeatExchanger.mo, Buildings/Fluid/Storage/Stratified.mo, Buildings/Fluid/Storage/StratifiedEnhancedInternalHex.mo
set mSenFac = 1 in storage tank
=> propagated allowFlowReversal and m_flow_small in storage tank models

Buildings/Electrical/Transmission/BaseClasses/BaseCable.mo, Buildings/Electrical/Transmission/BaseClasses/PartialBaseLine.mo, Buildings/Electrical/Transmission/MediumVoltageCables/Annealed_Al_10.mo, Buildings/Electrical/Transmission/MediumVoltageCables/Annealed_Al_1000.mo, Buildings/Electrical/Transmission/MediumVoltageCables/Annealed_Al_1500.mo, Buildings/Electrical/Transmission/MediumVoltageCables/Annealed_Al_30.mo, Buildings/Electrical/Transmission/MediumVoltageCables/Annealed_Al_350.mo, Buildings/Electrical/Transmission/MediumVoltageCables/Annealed_Al_40.mo, Buildings/Electrical/Transmission/MediumVoltageCables/Annealed_Al_500.mo, Buildings/Electrical/Transmission/MediumVoltageCables/Generic.mo
=> Replaced Tref by T_ref for #399

Buildings/Airflow/Multizone/UsersGuide/package.order, Buildings/Airflow/Multizone/package.order
Fixes parsing after merging 293bdf622814287478948536e6c335cee34cf51b.
=> Fix parsing

Buildings/Rooms/BaseClasses/CFDExchange.mo, Buildings/package.mo
=> Set start and fixed attribute for CFDExchange.u

Buildings/Fluid/FMI/Examples/FlowSplitter_u.mo, Buildings/Fluid/FMI/Examples/package.order, Buildings/Fluid/FMI/FlowSplitter_u.mo, Buildings/Resources/ReferenceResults/Dymola/Buildings_Fluid_FMI_Examples_FlowSplitter_u.txt, Buildings/Resources/Scripts/Dymola/Fluid/FMI/Examples/FlowSplitter_u.mos, Buildings/package.mo
Michael,
could you please review and merge this to the master. I also fixed some html issues which were in the documentation.
Thanks!
Thierry
=> Issue442 assert

Buildings/Rooms/BaseClasses/CFDExchange.mo, Buildings/package.mo
=> Issue459 cfd start values

Buildings/Fluid/Movers/Examples/MoverContinuous.mo, Buildings/Fluid/Movers/Examples/MoverParameter.mo, Buildings/Fluid/Movers/Examples/MoverStages.mo, Buildings/Fluid/Movers/Examples/package.order, Buildings/Fluid/Movers/FlowControlled_dp.mo, Buildings/Resources/Scripts/Dymola/Fluid/Movers/Examples/MoverContinuous.mos, Buildings/Resources/Scripts/Dymola/Fluid/Movers/Examples/MoverParameter.mos
=> Issue288 on off movers

Buildings/Fluid/Chillers/Carnot.mo, Buildings/package.mo
=> Issue468 carnot assert

Buildings/Fluid/Chillers/Carnot.mo, Buildings/package.mo
=> Bug fix for #476

Buildings/Fluid/Storage/BaseClasses/IndirectTankHeatExchanger.mo
unit tests in Buildings.Fluid.Storage are ok
fr #454
=> propagated two parameters in IndirectTankHeatExchanger for #454

Buildings/Electrical/Interfaces/PartialWindTurbine.mo, Buildings/HeatTransfer/Conduction/SingleLayer.mo, Buildings/HeatTransfer/Data/BaseClasses.mo, Buildings/Rooms/BaseClasses/MixedAirHeatGain.mo, Buildings/package.mo
=> Removed test of Real for equality. For #493

Buildings/BoundaryConditions/SolarGeometry/ProjectedShadowLength.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckCeilingHeight.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckPressure.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckSkyCover.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckTemperature.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckWindDirection.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckWindSpeed.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertRadiation.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertRelativeHumidity.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/Examples/GetHeaderElement.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/getAbsolutePath.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/getHeaderElementTMY3.mo, Buildings/BoundaryConditions/WeatherData/ReaderTMY3.mo, Buildings/Controls/DemandResponse/Examples/ClientLBNL90.mo, Buildings/Fluid/SolarCollectors/Validation/FlatPlate.mo, Buildings/HeatTransfer/Windows/BeamDepthInRoom.mo, Buildings/Rooms/BaseClasses/CFDExchange.mo, Buildings/Rooms/CFD.mo, Buildings/Rooms/FLEXLAB/Rooms/Examples/TestBedX3WithRadiantFloor.mo, Buildings/Rooms/FLEXLAB/Rooms/Examples/X3AWithRadiantFloor.mo, Buildings/Rooms/FLEXLAB/Rooms/Examples/X3BWithRadiantFloor.mo, Buildings/Rooms/Validation/LBNL_71T/RoomB/ElectroChromicWindow.mo, Buildings/package.mo
=> Issue506 get absolute path v2

Buildings/Fluid/FMI/FlowSplitter_u.mo
=> Remove assert statement.

Buildings/Fluid/Storage/Stratified.mo, Buildings/Fluid/Storage/StratifiedMultipleInlet.mo, Buildings/Fluid/Storage/package.order
Add possibility to have multiple inlets/outlets at customable places for storage tank model.
=> Issue529 tank

Buildings/Experimental/DistrictHeatingCooling/Plants/HeatingCoolingCarnot_T.mo
=> Added output signals for #541

Buildings/Rooms/Validation/BESTEST/Case900.mo, Buildings/Rooms/Validation/BESTEST/Case900FF.mo, Buildings/package.mo
=> Added missing parameter keyword for #543

Buildings/Fluid/Storage/Stratified.mo, Buildings/package.mo
=> Removed medium declaration. For #544

Buildings/Fluid/HeatExchangers/WetCoilCounterFlow.mo, Buildings/Fluid/HeatExchangers/WetCoilDiscretized.mo, Buildings/package.mo
=> Issue547 wetcoil medium

Buildings/BoundaryConditions/WeatherData/BaseClasses/getAbsolutePath.mo, Buildings/HeatTransfer/Windows/BeamDepthInRoom.mo, Buildings/Rooms/FLEXLAB/Rooms/Examples/TestBedX3WithRadiantFloor.mo, Buildings/Rooms/FLEXLAB/Rooms/Examples/X3BWithRadiantFloor.mo, Buildings/package.mo
=> Merged changes in weather data reader from Annex 60

Buildings/Electrical/AC/ThreePhasesUnbalanced/Sources/FixedVoltage.mo, Buildings/Electrical/AC/ThreePhasesUnbalanced/Sources/FixedVoltage_N.mo, Buildings/Electrical/AC/ThreePhasesUnbalanced/Validation/IEEETests/Test4NodesFeeder/package.mo, Buildings/Electrical/AC/package.mo, Buildings/Electrical/Interfaces/Source.mo, Buildings/Electrical/Interfaces/Terminal.mo, Buildings/Electrical/Interfaces/VariableVoltageSource.mo, Buildings/Electrical/PhaseSystems/package.mo, Buildings/Electrical/UsersGuide.mo, Buildings/Fluid/FixedResistances/SplitterFixedResistanceDpM.mo, Buildings/Fluid/HeatExchangers/Boreholes/BaseClasses/singleUTubeResistances.mo, Buildings/Fluid/SolarCollectors/BaseClasses/ASHRAESolarGain.mo, Buildings/Fluid/Storage/BaseClasses/ThirdOrderStratifier.mo, Buildings/Rooms/BaseClasses/ConstructionNumbers.mo, Buildings/Rooms/CFD.mo, Buildings/Rooms/Examples/FFD/Tutorial/NaturalConvection.mo, Buildings/Rooms/UsersGuide.mo, Buildings/package.mo
just some minor HTML fixes,
found using http://htmlhint.com/
=> minor HTML fixes

Buildings/Fluid/FMI/Adaptors/Inlet.mo, Buildings/HeatTransfer/Radiosity/BaseClasses/RadiosityTwoSurfaces.mo, Buildings/HeatTransfer/Radiosity/OpaqueSurface.mo, Buildings/HeatTransfer/Windows/BaseClasses/GlassLayer.mo, Buildings/HeatTransfer/Windows/Functions/devAbsInteriorIrradiationInteriorShading.mo
Merges issues detected by JModelica.
=> Issue510 refactor j modelica

.travis.yml, Buildings/Resources/Scripts/travis/usr/local/bin/dymola, README.md, bin/runUnitTests.py
This merges the continuous integration to the master branch.
=> Merge ci to master

Buildings/Resources/Scripts/travis/usr/local/bin/dymola
Update command line arguments for travis.
=> Updated command line arguments

.travis.yml
instead of using system_site_packages
https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
=> install scipy, numpy and matplotlib via pip

Buildings/Examples/Tutorial/Boiler/System1.mo, Buildings/Examples/Tutorial/Boiler/System2.mo, Buildings/Examples/Tutorial/Boiler/System3.mo, Buildings/Examples/Tutorial/Boiler/System4.mo, Buildings/Examples/Tutorial/Boiler/System5.mo, Buildings/Examples/Tutorial/Boiler/System6.mo, Buildings/Examples/Tutorial/Boiler/System7.mo
=> Added missing density for #673

Buildings/Fluid/FixedResistances/BaseClasses/Pipe.mo
RGB values should be in the range 0...255
OpenModelica was complaining about 256 being out of range
=> RGB values should be in the range 0...255

Buildings/Fluid/FixedResistances/LosslessPipe.mo, Buildings/Fluid/HeatPumps/Examples/package.mo, Buildings/Fluid/HeatPumps/Validation/package.mo, Buildings/Fluid/HeatPumps/package.mo, Buildings/Fluid/Movers/BaseClasses/IdealSource.mo, Buildings/Resources/Scripts/Dymola/Fluid/FixedResistances/Validation/PressureDropsSeries.mos
=> Annex60 sync

Buildings/.copiedFiles.txt, Buildings/Fluid/Types.mo
=> Ibpsa sync

Buildings/Fluid/Chillers/BaseClasses/Carnot.mo
Implementation according to your suggestions (hopefully) with correct names of the parameters, default values according to the discussion I had with Emerson and depending on cp_default.
=> Issue653 carnot dt

Buildings/Fluid/HeatPumps/Calibration/ScrollWaterToWater.mo, Buildings/Fluid/HeatPumps/package.mo, Buildings/Fluid/SolarCollectors/package.mo
=> Issue695 doc

Buildings/Experimental/OpenBuildingControl/CDL/Conversions/Validation/BooleanToInteger.mo, Buildings/Experimental/OpenBuildingControl/CDL/Conversions/Validation/BooleanToReal.mo, Buildings/Experimental/OpenBuildingControl/CDL/Discrete/Examples/TriggeredMax.mo, Buildings/Experimental/OpenBuildingControl/CDL/Discrete/Examples/TriggeredSampler.mo, Buildings/Experimental/OpenBuildingControl/CDL/Integers/Validation/OnCounter.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/And.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/And3.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Change.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Edge.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/FallingEdge.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Latch.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/LogicalSwitch.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Nand.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Nor.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Not.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/OnDelay.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Or.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Or3.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Switch.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Timer.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Toggle.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/TriggeredTrapezoid.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/Xor.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Validation/ZeroCrossing.mo, Buildings/Experimental/OpenBuildingControl/CDL/Sources/DutyCycle.mo, Buildings/Experimental/OpenBuildingControl/CDL/Sources/Validation/DutyCycle.mo, Buildings/Resources/Scripts/Dymola/Experimental/OpenBuildingControl/CDL/Discrete/Examples/DayType.mos
=> Changed the wrong unit in DutyCycle for #714

Buildings/Fluid/HeatExchangers/Ground/Boreholes/BaseClasses/Examples/BoreholeSegment.mo, Buildings/Fluid/HeatExchangers/Ground/Boreholes/Examples/UTube.mo
This closes #742 and should not change reference results.
=> Corrected parameters of experiment

Buildings/Resources/src/python/pythonInterpreter.c
This closes https://github.com/lbl-srg/modelica-buildings/pull/746
=> Tbeu py func

Buildings/Fluid/HeatExchangers/BaseClasses/HexElementLatent.mo, Buildings/Fluid/HeatExchangers/BaseClasses/HexElementSensible.mo
=> Corrected documentation for #749

Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/PartialDXCoil.mo
=> Added replaceable and cleaned up code

Buildings/Fluid/Chillers/Data/ElectricEIR.mo
=> Updated annotation for #830

Buildings/Fluid/Storage/Validation/HeatExchangerDynamics.mo, Buildings/Fluid/Storage/Validation/HeatExchangerLocation.mo
=> Added zero mass flow rate boundary condition

Buildings/Experimental/OpenBuildingControl/ASHRAE/G36/Constants/OperationModes/package.mo, Buildings/Experimental/OpenBuildingControl/CDL/Continuous/Limiter.mo, Buildings/Experimental/OpenBuildingControl/CDL/Discrete/TriggeredMax.mo
=> Issue848 omedit

Buildings/Experimental/OpenBuildingControl/ASHRAE/G36/Constants/OperationModes/package.mo
=> Reordered constants for #802

Buildings/Experimental/OpenBuildingControl/CDL/Logical/Or3.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Pre.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Timer.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/Toggle.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/TrueFalseHold.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/TrueHoldWithReset.mo, Buildings/Experimental/OpenBuildingControl/CDL/Logical/ZeroCrossing.mo
=> Added indicator for input or output signal

Buildings/Air/Systems/SingleZone/VAV/ChillerDXHeatingEconomizer.mo
@mwetter Minor change review.
This closes #908.
=> Removed wrong annotation

Buildings/Examples/VAVCO2/BaseClasses/DamperControl.mo, Buildings/Examples/VAVCO2/BaseClasses/Occupancy.mo, Buildings/Examples/VAVCO2/BaseClasses/RoomVAV.mo, Buildings/Examples/VAVCO2/BaseClasses/Suite.mo
=> Updated annotations, removed unused motor model

Buildings/Applications/DataCenters/ChillerCooled/Controls/ChillerStage.mo, Buildings/Applications/DataCenters/ChillerCooled/Controls/ConstantSpeedPumpStage.mo, Buildings/Applications/DataCenters/ChillerCooled/Controls/Validation/ChillerStage.mo, Buildings/Applications/DataCenters/ChillerCooled/Controls/VariableSpeedPumpStage.mo, Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/BaseClasses/PartialPlant.mo, Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/CoolingCoilHumidifyingHeating_ClosedLoop.mo, Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/IntegratedPrimaryLoadSide.mo, Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/IntegratedPrimaryPlantSide.mo, Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/IntegratedPrimarySecondary.mo, Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/NonIntegrated.mo, Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/WatersideEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimaryLoadSideEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimarySecondaryEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/NonIntegratedPrimarySecondaryEconomizer.mo
=> Revised selection of mode for JModelica

Buildings/Controls/OBC/ASHRAE/G36/Composite/Validation/EconomizerMultiZone_Mod_DamLim.mo, Buildings/Controls/OBC/ASHRAE/G36/Composite/Validation/EconomizerSingleZone_Disable.mo, Buildings/Controls/OBC/ASHRAE/G36/Composite/Validation/EconomizerSingleZone_Mod_DamLim.mo
=> Remove text annotation without a text string

Buildings/Controls/OBC/CDL/Continuous/Hysteresis.mo, Buildings/Controls/OBC/CDL/Discrete/ZeroOrderHold.mo
=> Issue990 hysteresis

Buildings/Controls/OBC/CDL/Logical/Latch.mo, Buildings/Controls/OBC/CDL/Logical/Toggle.mo
=> Converted algorithm to equation for #996

Buildings/BoundaryConditions/SolarGeometry/BaseClasses/SolarAzimuth.mo, Buildings/BoundaryConditions/SolarGeometry/BaseClasses/WallSolarAzimuth.mo, Buildings/Fluid/FMI/Conversion/Validation/InletToAirDryAir.mo, Buildings/Fluid/FMI/Conversion/Validation/InletToAirDryAirCO2.mo, Buildings/Fluid/FMI/Conversion/Validation/InletToAirMoistAirCO2.mo
Merge fixes for OpenModelica and changes to replace algorithm with equation section.
=> Merged IBPSA master

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/Economizers/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/Economizers/Subsequences/Limits.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/SetPoints/VAVSupplyFan.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/SetPoints/VAVSupplySignals.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/Economizers/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/Economizers/Subsequences/Modulation.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/Generic/FreezeProtectionMixedAir.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Reheat/DamperValves.mo
This adds more changes to #1056
=> Propagated Td

Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo, Buildings/ThermalZones/Detailed/BaseClasses/CFDExchange.mo, Buildings/ThermalZones/Detailed/CFD.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/1072
=> Tbeu fix load selector

Buildings/package.mo, README.md
=> Changed release notes

Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimarySecondaryEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/NonIntegratedPrimarySecondaryEconomizer.mo
=> Corrected conversion of enumeration. For #1083

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/Economizers/Subsequences/Limits.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/SetPoints/VAVSupplySignals.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Controller.mo
=> Improved documentation

Buildings/Experimental/DistrictHeatingCooling/Examples/BaseClasses/HeatingCoolingHotWater3Clusters.mo, Buildings/Experimental/DistrictHeatingCooling/SubStations/VaporCompression/HeatingCoolingHotwaterTimeSeries_dT.mo, Buildings/Experimental/DistrictHeatingCooling/SubStations/VaporCompression/Validation/HeatingCoolingHotwaterTimeSeries_dT.mo, Buildings/Experimental/DistrictHeatingCooling/Validation/HeatingCoolingHotWaterSmall.mo
=> Corrected call to loadResources

Buildings/Airflow/Multizone/EffectiveAirLeakageArea.mo, Buildings/Controls/OBC/CDL/Continuous/Sources/TimeTable.mo, Buildings/Controls/Predictors/ElectricalLoad.mo, Buildings/Electrical/AC/ThreePhasesUnbalanced/Sensors/BaseClasses/GeneralizedProbe.mo, Buildings/Electrical/DC/Loads/Resistor.mo, Buildings/Examples/ChillerPlant/BaseClasses/Controls/LinearPiecewiseTwo.mo, Buildings/Examples/ChillerPlant/package.mo, Buildings/Fluid/HeatExchangers/DXCoils/UsersGuide.mo, Buildings/Fluid/Interfaces/PartialTwoPortInterface.mo, Buildings/Fluid/Interfaces/StaticTwoPortHeatMassExchanger.mo, Buildings/Fluid/MixingVolumes/Examples/MixingVolumeMoistAir.mo, Buildings/Fluid/Movers/Data/Generic.mo, Buildings/HeatTransfer/Sources/FixedHeatFlow.mo, Buildings/HeatTransfer/Sources/FixedTemperature.mo, Buildings/HeatTransfer/Sources/PrescribedHeatFlow.mo, Buildings/HeatTransfer/Sources/PrescribedTemperature.mo, Buildings/HeatTransfer/Windows/Functions/glassPropertyUncoated.mo, Buildings/Media/Air.mo, Buildings/Media/Specialized/Air/PerfectGas.mo, Buildings/package.mo
=> fixed typos regarding incomplete brackets #1110

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/Economizers/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/SetPoints/VAVSupplyFan.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/ModeAndSetPoints.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/SetPoints/ZoneTemperatures.mo, Buildings/Controls/OBC/CDL/Continuous/package.mo, Buildings/Controls/OBC/CDL/Discrete/package.mo, Buildings/Controls/OBC/CDL/Integers/package.mo, Buildings/Controls/OBC/CDL/SetPoints/package.mo
=> Issue1115 obc documentation

Buildings/Controls/OBC/ASHRAE/G36_PR1/Types/DemandLimitLevels/package.order, Buildings/Controls/OBC/ASHRAE/G36_PR1/Types/FreezeProtectionStages/package.order, Buildings/Controls/OBC/ASHRAE/G36_PR1/Types/OperationModes/package.order, Buildings/Controls/OBC/ASHRAE/G36_PR1/Types/ZoneStates/package.order
This fixes OpenModelica refusing the open the master branch
=> Add missing constants in package.order

Buildings/Applications/DataCenters/ChillerCooled/Equipment/BaseClasses/PartialParallelElectricEIR.mo, Buildings/package.mo
@YangyangFu : Can you please review this change. (This also needs to be corrected in Fig. 3 of the paper.)
=> Added constrainedby for #1118

Buildings/Controls/OBC/CDL/Continuous/LimPID.mo
=> corrected icon layer line creation in LimPID

Buildings/BoundaryConditions/SolarGeometry/BaseClasses/AltitudeAngle.mo, Buildings/BoundaryConditions/SolarGeometry/BaseClasses/Declination.mo, Buildings/BoundaryConditions/SolarGeometry/BaseClasses/Examples/WallSolarAzimuth.mo, Buildings/BoundaryConditions/SolarGeometry/BaseClasses/IncidenceAngle.mo, Buildings/BoundaryConditions/SolarGeometry/BaseClasses/SolarAzimuth.mo, Buildings/BoundaryConditions/SolarGeometry/BaseClasses/SolarHourAngle.mo, Buildings/BoundaryConditions/SolarGeometry/BaseClasses/WallSolarAzimuth.mo, Buildings/BoundaryConditions/SolarGeometry/BaseClasses/ZenithAngle.mo, Buildings/BoundaryConditions/SolarGeometry/IncidenceAngle.mo, Buildings/BoundaryConditions/SolarGeometry/ZenithAngle.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/CheckRelativeHumidity.mo, Buildings/BoundaryConditions/WeatherData/BaseClasses/ConvertRelativeHumidity.mo, Buildings/Fluid/FixedResistances/Junction.mo, Buildings/Fluid/Interfaces/StaticTwoPortConservationEquation.mo
This merges changes from IBPSA to Buildings.
=> Merged IBPSA, branch issue905_png

Buildings/Utilities/IO/Python27/Functions/BaseClasses/PythonObject.mo, Buildings/Utilities/IO/Python27/Functions/BaseClasses/exchange.mo, Buildings/package.mo
=> Corrected LibraryDirectory annotation

Buildings/Fluid/BaseClasses/PartialThreeWayResistance.mo
Merge IBPSA library with new icons for valve
=> Merged IBPSA library

.travis.yml, Buildings/Resources/Scripts/travis/bin/dymola, Buildings/Resources/Scripts/travis/bin/jm_ipython.sh
=> Changed image and cleaned up code for #1185

Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_5_to_6.0.0.mos, Buildings/package.mo
=> Prepared for version 6.0.0 development

Buildings/Controls/Continuous/OffTimer.mo, Buildings/Controls/DemandResponse/Client.mo, Buildings/Electrical/DC/Sources/BaseClasses/WindCorrection.mo, Buildings/Examples/VAVCO2/BaseClasses/Occupancy.mo, Buildings/Fluid/Movers/BaseClasses/FlowMachineInterface.mo, Buildings/Fluid/Movers/BaseClasses/PowerInterface.mo, Buildings/HeatTransfer/Windows/BaseClasses/StateInterpolator.mo, Buildings/ThermalZones/Detailed/BaseClasses/to_W.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/1194
=> Beutlich fix obsoleted icon

Buildings/Media/Refrigerants/R410A/package.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/1219 with the upstream merge from IBPSA.
=> Merged IBPSA, branch issue991_constantDeclaration

Buildings/Occupants/Office/Blinds/Haldi2008BlindsTIn.mo, Buildings/Occupants/Office/Blinds/Haldi2008BlindsTOut.mo, Buildings/Occupants/Office/Blinds/Inkarojrit2008BlindsSIntensity.mo, Buildings/Occupants/Office/Blinds/Newsham1994BlindsSIntensity.mo, Buildings/Occupants/Office/Blinds/Zhang2012BlindsSAltitude.mo, Buildings/Occupants/Office/Blinds/Zhang2012BlindsSIntensity.mo, Buildings/Occupants/Office/Occupancy/Wang2005Occupancy.mo, Buildings/Occupants/Office/Windows/Haldi2009WindowsTInTout.mo, Buildings/Occupants/Office/Windows/Yun2008WindowsTIn.mo, Buildings/Occupants/Office/Windows/Yun2008WindowsTOut.mo, Buildings/Occupants/Residential/AirConditioning/Ren2014ACBedroom.mo, Buildings/Occupants/Residential/AirConditioning/Ren2014ACLivingroom.mo, Buildings/package.mo
1. Specify initial conditions
2. Update the release information
3. Verify the Zhang2012BlindsSAltitude model
=> obModelica Revision_0921

Buildings/Occupants/Office/Lighting/Gunay2016Light.mo, Buildings/Occupants/Office/Lighting/Reinhart2003Light.mo
Dear Michael.
Sorry again for the unit mistake, which has been fixed in this version.
Best and thanks, Zhe
=> Fixed the unit problem in two lighting models

Buildings/Fluid/HeatExchangers/DryCoilCounterFlow.mo, Buildings/Fluid/HeatExchangers/WetCoilCounterFlow.mo
=> Kinonotofu issue1258 wet coil counter flow

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/OutsideAirFlow.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/SupplyFan.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/LoadAggregation/aggregationWeightingFactors.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/Examples/TimeGeometric.mo
This PR merges the recent PR from @casella
=> Casella patch 1 7

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/Controller.mo
=> Added missing 'each'

Buildings/ThermalZones/Detailed/BaseClasses/MixedAirHeatMassBalance.mo
=> Changed call to enthalpyOfCondensingGas

Buildings/Applications/DataCenters/ChillerCooled/Equipment/IntegratedPrimaryLoadSide.mo, Buildings/Electrical/Transmission/BaseClasses/PartialNetwork.mo, Buildings/Fluid/SolarCollectors/BaseClasses/EN12975SolarGain.mo, Buildings/Utilities/IO/BCVTB/BCVTB.mo
=> Issue1300 missing each

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/OutsideAirFlow.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/Generic/SetPoints/OperationMode.mo, Buildings/Controls/OBC/CDL/Continuous/MultiMax.mo, Buildings/Controls/OBC/CDL/Continuous/MultiMin.mo, Buildings/Controls/OBC/CDL/Continuous/MultiSum.mo, Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_5_to_6.0.0.mos, Buildings/package.mo
@mwetter: Please review the changes:
MultiMax block & MultiMin block:
- changed the output variable name yMax/yMin to y
- changed the icon image
- updated the Version_6_0_0 notes for those changes
MultiSum block:
- changed the size of the input arrow
=> Issue1252 multimax

.travis.yml
=> Specified python version

Buildings/package.mo
=> Corrected release notes

Buildings/Resources/C-Sources/exchangeValues.c, Buildings/Resources/C-Sources/externalObjectStructure.h, Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/C-Sources/plotObjectStructure.h
=> Added missing include statements

Buildings/Resources/C-Sources/cfdStartCosimulation.c
=> Corrected type conversion for #1338

Buildings/Occupants/BaseClasses/exponentialVariableGeneration.mo, Buildings/Occupants/BaseClasses/weibullVariableGeneration.mo, Buildings/Occupants/Office/Blinds/Zhang2012BlindsSolarAltitude.mo, Buildings/Occupants/Office/Blinds/Zhang2012BlindsSolarIntensity.mo, Buildings/Occupants/Office/Windows/Haldi2009WindowsTInTout.mo, Buildings/Occupants/Office/Windows/Herkel2008WindowsCompletelyOpen.mo, Buildings/Occupants/Office/Windows/Herkel2008WindowsSmall.mo, Buildings/Occupants/Office/Windows/Herkel2008WindowsTiltedOpen.mo, Buildings/Occupants/Office/Windows/Zhang2012WindowsAll.mo, Buildings/Occupants/Office/Windows/Zhang2012WindowsEast.mo, Buildings/Occupants/Office/Windows/Zhang2012WindowsNorth.mo, Buildings/Occupants/Office/Windows/Zhang2012WindowsSouth.mo, Buildings/Occupants/Office/Windows/Zhang2012WindowsWest.mo
=> Corrected special character for #1357

Buildings/Controls/OBC/OutdoorLights/DaylightControlled.mo, Buildings/Controls/OBC/OutdoorLights/Validation/DaylightControlled.mo, Buildings/Controls/OBC/OutdoorLights/package.mo
@mwetter Please review:
- Changed instance name and default component name
- Reformatted info section in package.mo
=> issue1364 Outdoor Lights control

Buildings/Controls/OBC/ASHRAE/G36_PR1/Generic/SetPoints/OperationMode.mo, Buildings/package.mo
=> Corrected wrong documentation in the parameter for #1409

Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_5_to_6.0.0.mos
=> Corrected package name for #1431

.travis.yml, Buildings/Resources/Scripts/travis/bin/jm_ipython.sh
=> Updated docker image name for #1450

Buildings/Controls/OBC/CDL/Discrete/MovingMean.mo, Buildings/Resources/Scripts/Dymola/Controls/OBC/CDL/Discrete/Examples/MovingMean.mos, Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Controls.OBC.CDL.Discrete.Examples.MovingMean.mos
@mwetter 
I implemented the block using algorithm. Please review.
=> Discrete moving mean

Buildings/Fluid/Chillers/BaseClasses/PartialElectric.mo
=> Removed start and nominal attribute for #1465

Buildings/Utilities/Plotters/Examples/SingleZoneVAV.mo, Buildings/package.mo
=> Issue1489 new lib dev

Buildings/package.mo
I noticed when reading the release notes from https://github.com/lbl-srg/modelica-buildings/releases/tag/v6.0.0
=> Fix wording

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Economizers/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Economizers/Subsequences/Modulation.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Validation.mo
@dhblum 
The updates are what we have discussed today; you can start from this update
=> Issue1265 sz controller

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/OutsideAirFlow.mo
This improves the documentation. 
@JayHuLBL : Can you please review.
=> Documentation multizone vav setpoints outside air flow

Buildings/Resources/C-Sources/EnergyPlus/BuildingInstantiate.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusStructure.c, Buildings/Resources/C-Sources/EnergyPlus/ZoneAllocate.c, Buildings/Resources/C-Sources/EnergyPlus/ZoneExchange.c, Buildings/Resources/C-Sources/EnergyPlus/ZoneFree.c, Buildings/Resources/C-Sources/EnergyPlus/ZoneInstantiate.c
This merges the new print statements to the fmi signature development branch because the ones on the base branch do not show properly in Dymola.
=> Issue1129 energy plus zone fmi signature seg fault dymola

Buildings/Experimental/EnergyPlus/BaseClasses/FMUZoneClass.mo, Buildings/Experimental/EnergyPlus/package.mo
Merge changes for Dymola 2020 to branch with FMI API.
=> Corrected 'extends Modelica.Icons statements for Dymola 2020

Buildings/Resources/C-Sources/EnergyPlus/BuildingInstantiate.c
This properly sets the fmukind flag.
=> Set fmu kind

Buildings/Resources/C-Sources/EnergyPlus/BuildingInstantiate.c, Buildings/Resources/C-Sources/EnergyPlus/BuildingInstantiate.h, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusStructure.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusStructure.h, Buildings/Resources/C-Sources/EnergyPlus/ZoneExchange.c, Buildings/Resources/C-Sources/EnergyPlus/ZoneFree.c
=> Avoided multiple generation of FMU

Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/CoolingCapacityWaterCooled.mo, Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/PartialCoolingCapacity.mo
=> Avoided divsion by zero

Buildings/Air/Systems/SingleZone/VAV/ChillerDXHeatingEconomizer.mo, Buildings/Air/Systems/SingleZone/VAV/ChillerDXHeatingEconomizerController.mo, Buildings/Air/Systems/SingleZone/VAV/Examples/BaseClasses/PartialOpenLoop.mo, Buildings/Air/Systems/SingleZone/VAV/Examples/BaseClasses/Room.mo, Buildings/Air/Systems/SingleZone/VAV/Examples/ChillerDXHeatingEconomizer.mo, Buildings/Air/Systems/SingleZone/VAV/Examples/Guideline36.mo
Updated parameters in both models so that they are more comparable.
=> SZVAV compare updates

Buildings/BoundaryConditions/WeatherData/ReaderTMY3.mo, Buildings/Controls/OBC/CDL/Continuous/Sources/CalendarTime.mo, Buildings/Controls/OBC/CDL/Types/ZeroTime.mo, Buildings/Fluid/Actuators/BaseClasses/ActuatorSignal.mo, Buildings/Fluid/Actuators/BaseClasses/PartialThreeWayValve.mo, Buildings/Fluid/Actuators/BaseClasses/PartialTwoWayValve.mo, Buildings/Fluid/Actuators/BaseClasses/PartialTwoWayValveKv.mo, Buildings/Fluid/Actuators/Valves/TwoWayPressureIndependent.mo, Buildings/Fluid/BaseClasses/PartialResistance.mo, Buildings/Fluid/Movers/BaseClasses/PartialFlowMachine.mo, Buildings/Utilities/Time/CalendarTime.mo, Buildings/Utilities/Time/Types/ZeroTime.mo, Buildings/package.mo
Merges update to `CalendarTime`.
This closes #1600, #1601, #1602, #1603, #1604, #1605
=> Merged IBPSA

Buildings/Fluid/MixingVolumes/BaseClasses/PartialMixingVolume.mo
=> Improved error message

Buildings/Resources/Scripts/BuildingsPy/conf.json
=> Removed models from the exclude list

Buildings/Controls/OBC/CDL/Discrete/TriggeredMovingMean.mo, Buildings/Obsolete/Controls/OBC/CDL/Discrete/MovingMean.mo, Buildings/Obsolete/Controls/OBC/CDL/Discrete/package.mo, Buildings/Obsolete/Controls/OBC/CDL/package.mo, Buildings/Obsolete/Controls/OBC/package.mo, Buildings/Obsolete/Controls/package.mo, Buildings/package.mo
@mwetter:
Please review the following updates:
- removed unsuitable documentation in the obsolete package for the block MovingMean;
- added the obsolete message;
- added an entry in the non-backward compatible table;
=> Issue1588 moving mean trigger

Buildings/Fluid/SolarCollectors/BaseClasses/PartialSolarCollector.mo, Buildings/package.mo
This closes #1636 
This closes https://github.com/lbl-srg/modelica-buildings/pull/1637
Todo:
=> Issue1636 solar

Buildings/Controls/OBC/CDL/Logical/Pre.mo
=> Added icon name for #1570

Buildings/Resources/C-Sources/EnergyPlus/ZoneExchange.c
=> Issue1650 spawn test for nan

Buildings/Experimental/EnergyPlus/Building.mo, Buildings/Experimental/EnergyPlus/Examples/VAVReheatRefBldgSmallOffice/FloorOpenLoop.mo, Buildings/Experimental/EnergyPlus/ThermalZone.mo, Buildings/Experimental/EnergyPlus/Validation/OneZone.mo, Buildings/Experimental/EnergyPlus/Validation/OneZoneWithControl.mo, Buildings/Experimental/EnergyPlus/Validation/RefBldgSmallOffice.mo, Buildings/Experimental/EnergyPlus/Validation/TwoIdenticalZones.mo
=> Replaced volume with dynamic balance

.travis.yml, Buildings/Resources/Scripts/travis/bin/dymola
=> Updated files for Dymola 2020x

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Controller.mo
=> Refactored text, #1674

Buildings/Resources/C-Sources/EnergyPlus/BuildingInstantiate.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusStructure.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusStructure.h, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusUtil.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusUtil.h, Buildings/Resources/C-Sources/EnergyPlus/ZoneAllocate.c, Buildings/Resources/C-Sources/EnergyPlus/ZoneAllocate.h
=> Added high level function for char* malloc

Buildings/Resources/C-Sources/EnergyPlus/BuildingInstantiate.c
Changed variable declaration to avoid compiler warning.
=> Avoided compiler warning

Buildings/Resources/Scripts/Dymola/Examples/VAVCO2/VAVSystemCTControl.mos
Changed solver to CVode as this is also used in JModelica
=> Change solver to CVode

Buildings/Resources/Scripts/Dymola/Controls/OBC/CDL/Discrete/Examples/DayType.mos
=> removed git compare record, #1661

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/OutsideAirFlow.mo
=> Removed use of fill with unit assignment

Buildings/ThermalZones/Detailed/Constructions/Examples/ExteriorWallTwoWindows.mo, Buildings/ThermalZones/Detailed/Constructions/Examples/ExteriorWallWithWindow.mo, Buildings/package.mo
=> Corrected wrong parameter assignment

Buildings/Resources/C-Sources/getTimeSpan.h
=> Included header file in getTimeSpan.c

Buildings/Examples/Tutorial/CDL/Controls/EquipmentOnOff.mo, Buildings/Examples/Tutorial/CDL/Controls/OpenLoopEquipmentOnOff.mo, Buildings/Examples/Tutorial/CDL/Controls/OpenLoopSystemOnOff.mo, Buildings/Examples/Tutorial/CDL/Controls/RadiatorSupply.mo, Buildings/Examples/Tutorial/CDL/Controls/SystemOnOff.mo, Buildings/Examples/Tutorial/CDL/Controls/Validation/EquipmentOnOff.mo, Buildings/Examples/Tutorial/CDL/Controls/Validation/SystemOnOff.mo, Buildings/Examples/Tutorial/CDL/System2.mo, Buildings/Examples/Tutorial/CDL/System3.mo, Buildings/Examples/Tutorial/CDL/System4.mo, Buildings/Examples/Tutorial/CDL/package.mo, Buildings/Fluid/HeatExchangers/Radiators/RadiatorEN442_2.mo
This is ready to merge when all tests passed.
=> Issue1781 update cdl tutorial

Buildings/Controls/OBC/CDL/Continuous/LimPID.mo, Buildings/Controls/OBC/CDL/Continuous/Line.mo
=> Rendered output signal for #1785

Buildings/Examples/VAVReheat/Controls/ModeSelector.mo
=> Corrected morPreCoo(nIn=2) to nIn=1

Buildings/Controls/DemandResponse/Client.mo, Buildings/Examples/VAVReheat/Controls/ModeSelector.mo
=> Set nIn=0 in state machine initial steps if there is no input

Buildings/Air/Systems/SingleZone/VAV/Examples/ChillerDXHeatingEconomizer.mo, Buildings/Air/Systems/SingleZone/VAV/Examples/Guideline36.mo, Buildings/Controls/OBC/CDL/Interfaces/BooleanInput.mo, Buildings/Controls/OBC/CDL/Interfaces/BooleanOutput.mo, Buildings/Controls/OBC/CDL/Interfaces/DayTypeInput.mo, Buildings/Controls/OBC/CDL/Interfaces/DayTypeOutput.mo, Buildings/Controls/OBC/CDL/Interfaces/IntegerInput.mo, Buildings/Controls/OBC/CDL/Interfaces/IntegerOutput.mo, Buildings/Controls/OBC/CDL/Interfaces/RealInput.mo, Buildings/Controls/OBC/CDL/Interfaces/RealOutput.mo, Buildings/Examples/VAVReheat/Controls/Economizer.mo, Buildings/Examples/VAVReheat/Controls/FanVFD.mo, Buildings/Fluid/FixedResistances/Examples/FlowJunction.mo, Buildings/Fluid/FixedResistances/Validation/FlowJunctionSteadyState.mo, Buildings/Fluid/FixedResistances/Validation/FlowJunctionSteadyStateNoPressureDrop.mo, Buildings/Fluid/HeatPumps/Compressors/BaseClasses/PartialCompressor.mo, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/Generic.mo, Buildings/Fluid/MixingVolumes/Validation/BaseClasses/MixingVolumeReverseFlow.mo, Buildings/Fluid/SolarCollectors/ASHRAE93.mo, Buildings/Fluid/SolarCollectors/BaseClasses/ASHRAEHeatLoss.mo, Buildings/Fluid/SolarCollectors/BaseClasses/EN12975HeatLoss.mo, Buildings/Fluid/SolarCollectors/BaseClasses/PartialHeatLoss.mo, Buildings/Fluid/SolarCollectors/EN12975.mo, Buildings/Fluid/Sources/TraceSubstancesFlowSource.mo, Buildings/ThermalZones/ReducedOrder/Validation/VDI6007/BaseClasses/VerifyDifferenceThreePeriods.mo, Buildings/package.mo
=> Corrected broken hyperlinks

Buildings/Examples/Tutorial/CDL/Controls/OpenLoopRadiatorSupply.mo, Buildings/Examples/Tutorial/CDL/Controls/RadiatorSupply.mo
This corrects the typo in the tutorial.
This closes #1810
=> Corrected typo

Buildings/Controls/OBC/CDL/Continuous/LimPID.mo, Buildings/package.mo
=> Corrected unit declaration for gain k

Buildings/package.mo
This updates the release notes for the steam medium model.
=> Updated release notes

Buildings/Controls/OBC/CDL/Continuous/Validation/Hysteresis.mo
=> Corrected paths to fullpaths in CDL hysteresis block

Buildings/Resources/C-Sources/EnergyPlus/FMI2/fmi2TypesPlatform.h
=> Added defines to avoid redefinition

Buildings/Electrical/AC/OnePhase/Storage/Battery.mo, Buildings/Electrical/AC/ThreePhasesBalanced/Storage/Battery.mo, Buildings/package.mo
=> Corrected power drawn from electrical connector

Buildings/Controls/OBC/CDL/Continuous/Limiter.mo
=> Cleaned up implementation for #1882

Buildings/Controls/OBC/CDL/Continuous/Feedback.mo, Buildings/Controls/OBC/CDL/Continuous/Validation/Feedback.mo
=> Cleaned up graphic for #1880

Buildings/Controls/OBC/CDL/Continuous/Derivative.mo
Improves the documentation of the derivative block.
=> Updated documentation

Buildings/ThermalZones/EnergyPlus/UsersGuide.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/1901
=> Kuzha issue1129 energy plus zone

Buildings/ThermalZones/EnergyPlus/UsersGuide.mo
@mwetter 
I have added a note entry for weather file in the UsersGuide.
=> issue1129 Energyplus zone

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/OutdoorAirFlow/package.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Validation/ModeAndSetPoints.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartHeating.mo, Buildings/ThermalZones/Detailed/Validation/Initialization/MixedAir.mo
=> Corrected hyperlink

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/ExhaustDamper.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/ReturnFanDirectPressure.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/CoolingCoil.mo, Buildings/Controls/OBC/CDL/Continuous/LimPID.mo, Buildings/Controls/OBC/CDL/Continuous/Validation/LimPID.mo, Buildings/Controls/OBC/CDL/Continuous/Validation/LimPIDInitialDerivativeOutput.mo, Buildings/Controls/OBC/CDL/Continuous/Validation/LimPIDInitialState.mo, Buildings/Controls/OBC/CDL/Continuous/Validation/LimPIDWithReset.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartCoolingNegativeStartTime.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartCoolingPositiveStartTime.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartHeating.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartHeatingCooling.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartNoHeatingNoCooling.mo, Buildings/Examples/DualFanDualDuct/Controls/RoomMixingBox.mo, Buildings/Examples/Tutorial/Boiler/System5.mo, Buildings/Examples/Tutorial/Boiler/System6.mo, Buildings/Examples/Tutorial/Boiler/System7.mo, Buildings/Examples/Tutorial/CDL/Controls/BoilerReturn.mo, Buildings/Examples/VAVReheat/Controls/RoomVAV.mo, Buildings/Fluid/HeatExchangers/CoolingTowers/Examples/Merkel.mo, Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_6_to_7.0.0.mos, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600.mo, Buildings/ThermalZones/Detailed/Validation/BaseClasses/SingleZoneFloorHeater.mo, Buildings/Utilities/Plotters/Examples/BaseClasses/CoolingCoilValve.mo, Buildings/package.mo
=> Change default limits in CDL.Continuous.LimPID

.travis.yml
This is due to https://travis-ci.com/github/lbl-srg/modelica-buildings/jobs/329415902
=> Changed linux distribution

Buildings/Fluid/HeatExchangers/BaseClasses/HexElementLatent.mo, Buildings/Fluid/HeatExchangers/WetCoilCounterFlow.mo
=> Issue1920 wet coil simplify m wat flow

Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/DryWetSelector.mo, Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/Evaporation.mo, Buildings/package.mo
=> Corrected min/max attributes

Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_6_to_7.0.0.mos
These models did not have the parameter m_flow_small.
=> Removed medium column from conversion script.

Buildings/Fluid/CHPs/Data/package.mo
=> deleted broken link

Buildings/package.mo
This updates the participant list for the next release.
=> Updated participant list

Buildings/Fluid/HeatExchangers/RadiantSlabs/BaseClasses/Functions/AverageResistance.mo, Buildings/package.mo
This closes #2009
It also changes the print statement to an assertion with level set to warning.
=> Correct test on alpha

Buildings/Air/Systems/SingleZone/VAV/Examples/BaseClasses/PartialOpenLoop.mo, Buildings/Air/Systems/SingleZone/VAV/Examples/Guideline36.mo
This is needed for the OBC final report
=> Rearranged icons, removed non-used block for occupant density

Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusFMU.c, Buildings/ThermalZones/EnergyPlus/BaseClasses/PartialEnergyPlusObject.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/Validation/FMUZoneAdapterZones1.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/Validation/FMUZoneAdapterZones2.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/Validation/FMUZoneAdapterZones3.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/Writer.mo, Buildings/ThermalZones/EnergyPlus/Building.mo, Buildings/ThermalZones/EnergyPlus/Examples/VAVReheatRefBldgSmallOffice/FloorOpenLoop.mo, Buildings/ThermalZones/EnergyPlus/OutputVariable.mo, Buildings/ThermalZones/EnergyPlus/ThermalZone.mo, Buildings/ThermalZones/EnergyPlus/Validation/Actuator/LightsControl.mo, Buildings/ThermalZones/EnergyPlus/Validation/Actuator/ShadeControl.mo
This closes #1571.
The destructor is now invoked through `ModelicaFormatError`.
=> Issue1571 wrong weather file

Buildings/Controls/OBC/CDL/Logical/IntegerSwitch.mo, Buildings/Controls/OBC/CDL/Logical/LogicalSwitch.mo, Buildings/Controls/OBC/CDL/Logical/Switch.mo
=> Issue2033 switch icon

Buildings/Resources/C-Sources/EnergyPlus/BuildingInstantiate.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusFMU.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusTypes.h, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusUtil.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusUtil.h, Buildings/Resources/Library/linux64/libepfmi-9.0.1.so, Buildings/Resources/bin/spawn-linux64/bin/spawn, Buildings/Resources/bin/spawn-linux64/lib/epfmi.so, Buildings/Resources/src/ThermalZones/EnergyPlus/FMUs/RoomModel.mo, Buildings/Resources/src/ThermalZones/EnergyPlus/FMUs/Zones1.fmu, Buildings/Resources/src/ThermalZones/EnergyPlus/FMUs/Zones1.mo, Buildings/Resources/src/ThermalZones/EnergyPlus/FMUs/Zones3.fmu, Buildings/Resources/src/ThermalZones/EnergyPlus/FMUs/jmodelica.py, Buildings/ThermalZones/EnergyPlus/Types/Verbosity.mo, Buildings/ThermalZones/EnergyPlus/Validation/Actuator/LightsControl.mo, Buildings/ThermalZones/EnergyPlus/Validation/ThermalZone/OneZone.mo
=> Added logging for #2012

Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUZoneClass.mo, Buildings/ThermalZones/EnergyPlus/ThermalZone.mo
=> Updated models for omc

Buildings/ThermalZones/EnergyPlus/UsersGuide.mo
=> Issue2070 warm up description

Buildings/Electrical/Transmission/Functions/Validation/SelectCable_low.mo, Buildings/Electrical/Transmission/Functions/Validation/SelectCable_med.mo, Buildings/Electrical/Transmission/Functions/Validation/package.mo, Buildings/Electrical/Transmission/Functions/Validation/package.order, Buildings/Electrical/Transmission/Functions/package.order, Buildings/Resources/ReferenceResults/Dymola/Buildings_Electrical_Transmission_Functions_Validation_SelectCable_low.txt, Buildings/Resources/ReferenceResults/Dymola/Buildings_Electrical_Transmission_Functions_Validation_SelectCable_med.txt, Buildings/Resources/Scripts/Dymola/Electrical/Transmission/Functions/Validation/SelectCable_low.mos, Buildings/Resources/Scripts/Dymola/Electrical/Transmission/Functions/Validation/SelectCable_med.mos, Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Electrical.Transmission.Functions.Validation.SelectCable_low.mos, Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Electrical.Transmission.Functions.Validation.SelectCable_med.mos
=> Added unit test for #2095

Buildings/ThermalZones/Detailed/BaseClasses/PartialSurfaceInterface.mo
This PR improves the assertion message if a room area is set to 0.
=> Improved assertion message to include instance name

Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_7_to_8.0.0.mos
=> added semicolons, fixes #2098

Buildings/Controls/OBC/CDL/Conversions/BooleanToInteger.mo, Buildings/Controls/OBC/CDL/Conversions/BooleanToReal.mo
=> Updated icons for #2108

Buildings/Fluid/CHPs/BaseClasses/Validation/StandBy.mo
There is only one connection.
This will give an error in Dymola 2021x beta1
=> Removed wrong assignment pumOn(nOut=2).

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.json
=> Update to Optimica r17595

Buildings/Examples/Tutorial/Boiler/System3.mo
This corrects a wrong temperature in the documentation. The model uses 60 degC.
=> Corrected wrong documentation

Buildings/HeatTransfer/Sources/FixedHeatFlow.mo, Buildings/HeatTransfer/Sources/FixedTemperature.mo, Buildings/HeatTransfer/Sources/PrescribedHeatFlow.mo, Buildings/HeatTransfer/Sources/PrescribedTemperature.mo
This adds default component names.
=> Added missing default component name

Buildings/Resources/ReferenceResults/Dymola/Buildings_ThermalZones_EnergyPlus_Examples_VAVReheatRefBldgSmallOffice_FloorOpenLoop.txt, Buildings/Resources/ReferenceResults/Dymola/Buildings_ThermalZones_EnergyPlus_Validation_Actuator_ShadeControl.txt, Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUZoneAdapter.mo, Buildings/ThermalZones/EnergyPlus/Examples/VAVReheatRefBldgSmallOffice/FloorOpenLoop.mo, Buildings/ThermalZones/EnergyPlus/ThermalZone.mo
This adds dynamic calculation of the inlet temperature and mass flow rates that are already sent to EnergyPlus.
=> Issue1129 energy plus zone patch m inlet flow

Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/MinimumFlowBypass/FlowSetpoint.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Pumps/ChilledWater/Controller.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Pumps/ChilledWater/Validation/Controller.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Pumps/CondenserWater/Controller.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Pumps/CondenserWater/Validation/Controller.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/Processes/Down.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/Processes/Subsequences/DownStart.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/Processes/Subsequences/UpEnd.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/Processes/Up.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/SetPoints/SetpointController.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/SetPoints/Subsequences/Down.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/SetPoints/Subsequences/FailsafeCondition.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/SetPoints/Subsequences/Up.mo, Buildings/Controls/OBC/ASHRAE/PrimarySystem/ChillerPlant/Staging/SetPoints/Subsequences/Validation/FailsafeCondition.mo
=> Issue2165 is to have

Buildings/Examples/VAVReheat/Guideline36.mo
This closes #2066.
This is ready to merge when all tests pass.
=> Remove final modifier for VDisSetMin_flow

Buildings/Controls/OBC/CDL/Discrete/TriggeredMovingMean.mo
This removes a non-used protected parameter.
=> Removed non-used protected parameter t0

Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUInputVariableClass.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUOutputVariableClass.mo, Buildings/ThermalZones/EnergyPlus/ThermalZone.mo, Buildings/ThermalZones/EnergyPlus/package.mo
=> Reformulated model for #2221

.travis.yml
This is due to #2233 so that other tests can run.
=> Temporarily removed OMC, see #2233

Buildings/BoundaryConditions/WeatherData/BaseClasses/PartialLimiter.mo, Buildings/Fluid/Interfaces/Examples/ReverseFlowHumidifier.mo, Buildings/Fluid/Interfaces/Examples/ReverseFlowMassExchanger.mo, Buildings/Fluid/Sensors/BaseClasses/PartialAbsoluteSensor.mo
This merges corrections to the html code and brackets in the documentation from the IBPSA library.
=> Corrected html and documentation

Buildings/BoundaryConditions/WeatherData/BaseClasses/PartialLimiter.mo, Buildings/Fluid/Actuators/BaseClasses/PartialDamperExponential.mo, Buildings/Fluid/Examples/Performance/Example2.mo, Buildings/Fluid/MixingVolumes/Validation/TraceSubstanceConservationDynamicBalance.mo
This corrects html errors and a missing bracket on the maintenance branch.
=> Corrected html code and missing bracket in info section

.github/workflows/sync_gmt_mbl_master.yml
=> Add github action for nightly sync with the master

Buildings/Fluid/HeatExchangers/BaseClasses/lmtd.mo
=> Improved documentation for #2268

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/ExhaustDamper.mo, Buildings/Controls/OBC/CDL/Logical/And3.mo, Buildings/Controls/OBC/CDL/Logical/Or3.mo
=> Corrected typos in connector comment

Buildings/Fluid/HeatExchangers/BaseClasses/CoilRegister.mo
=> removed redundant annotation in class Fluid.HeatExchangers.BaseClasses.CoilRegister

Buildings/Controls/OBC/CDL/Continuous/PID.mo, Buildings/Controls/OBC/CDL/Continuous/PIDWithReset.mo
Changed comment to make clearer how the parameter is used
=> Improved comment

Buildings/Examples/ChillerPlant/DataCenterContinuousTimeControl.mo, Buildings/Examples/ChillerPlant/package.mo
Corrected typo in info section, rearranged block layout
=> Minor edits to layout and correction of typo

Buildings/Resources/bin/spawn-linux64/bin/spawn, Buildings/Resources/bin/spawn-linux64/lib/epfmi.so, Buildings/Resources/bin/spawn-win64/bin/epfmi.dll, Buildings/Resources/src/ThermalZones/EnergyPlus/install.py, Buildings/ThermalZones/EnergyPlus/UsersGuide.mo
=> Updated binary for reporting supported output variables

Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/Examples/WetCoil.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/2328
It adds `parameter` for the parameter record.
=> Patch wet coil parameter

Buildings/Controls/OBC/CDL/Integers/Change.mo, Buildings/package.mo
=> Corrected initialization of input u in CDL.Integer.Change

Buildings/Examples/VAVReheat/ASHRAE2006.mo, Buildings/Examples/VAVReheat/Guideline36.mo
This removes a duplicate connection that is already done in the base class.
=> Remove duplicate connection

Buildings/Controls/OBC/CDL/Continuous/Greater.mo, Buildings/Controls/OBC/CDL/Continuous/GreaterThreshold.mo, Buildings/Controls/OBC/CDL/Continuous/Less.mo, Buildings/Controls/OBC/CDL/Continuous/LessThreshold.mo, Buildings/package.mo
=> Correct documentation of hysteresis in comparison blocks

Buildings/Experimental/DHC/Loads/Examples/BaseClasses/BuildingSpawnZ1.mo, Buildings/Experimental/DHC/Loads/Examples/BaseClasses/BuildingSpawnZ6.mo, Buildings/ThermalZones/EnergyPlus/Examples/SmallOffice/NoHVAC.mo, Buildings/ThermalZones/EnergyPlus/ThermalZone.mo, Buildings/package.mo
This closes #2384.
The release date will be updated when I prepare the release.
=> Issue2348 documentation update

bin/cleanmodelica.py, bin/validateHTML.py, bin/verifyFiles.py
This corrects the python import statement, and uses the same import statements across all python scripts.
=> Corrected import statement

Buildings/ThermalZones/EnergyPlus/Building.mo, Buildings/ThermalZones/EnergyPlus/ThermalZone.mo
This clarifies where the idf name has to be specified for Spawn.
=> Clarfied documentation for where idf file is obtained from

Buildings/Controls/SetPoints/OccupancySchedule.mo
Merge refactored occupancy model to Spawn development.
=> Issue2369 ashrae2006 optimica occupied

Buildings/Resources/C-Sources/getTimeSpan.c, Buildings/Resources/C-Sources/getTimeSpan.h
This closes https://github.com/lbl-srg/modelica-buildings/issues/2374
=> Corrected possible memory violation

Buildings/Resources/C-Sources/EnergyPlusWrapper.c, Buildings/Resources/C-Sources/EnergyPlusWrapper.h, Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus.so, Buildings/Resources/Library/win64/ModelicaBuildingsEnergyPlus.dll, Buildings/Resources/Library/win64/ModelicaBuildingsEnergyPlus.lib, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/SpawnObjectInstantiate.c, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/SpawnObjectInstantiate.h, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/SpawnUtil.c, Buildings/ThermalZones/EnergyPlus/Actuator.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/PartialEnergyPlusObject.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/SpawnExternalObject.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/Synchronize/ObjectSynchronizer.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/Synchronize/SynchronizeBuilding.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/Synchronize/package.order, Buildings/ThermalZones/EnergyPlus/BaseClasses/ThermalZoneAdapter.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/getParameters.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/initialize.mo, Buildings/ThermalZones/EnergyPlus/Building.mo, Buildings/ThermalZones/EnergyPlus/OutputVariable.mo, Buildings/ThermalZones/EnergyPlus/Schedule.mo
This merges some cleanup for Spawn to the master.
=> Cleaned up code

Buildings/Fluid/HeatExchangers/BaseClasses/HexElementLatent.mo
=> Checked out file from issue2387_HexElement to correct modification of protected constant

Buildings/Fluid/HeatExchangers/BaseClasses/HexElementLatent.mo
=> Changed constant to public

Buildings/Fluid/HeatExchangers/WetCoilCounterFlow.mo
=> Removed final in redeclaration for #2392

Buildings/Experimental/DHC/Loads/BaseClasses/Validation/BuildingWithETS.mo, README.md
=> Changed steam medium for #2395

bin/runUnitTests.py
This function throws an exception. It has no return value
=> Corrected return value

Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus.so, Buildings/Resources/Library/win64/ModelicaBuildingsEnergyPlus.dll, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/BuildingInstantiate.c
=> Issue2410 spawn fmi log level

Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilDryWetRegime.mo, Buildings/Fluid/HeatExchangers/WetCoilEffectivenessNTU.mo
@AntoineGautier : Would this address https://github.com/lbl-srg/modelica-buildings/pull/2364#discussion_r602607111 ? If it causes an event, we could try adding `noEvent()`. Please merge if this addresses it.
=> Added dryFra as a public variable

Buildings/Resources/C-Sources/cryptographicsHash.c, Buildings/Resources/C-Sources/getTimeSpan.c, Buildings/Resources/C-Sources/getTimeSpan.h
This integrates the changes from https://github.com/lbl-srg/modelica-buildings/pull/2418
=> Correct memory leak

Buildings/Experimental/DHC/EnergyTransferStations/Combined/Generation5/Controls/PIDWithEnable.mo, Buildings/Experimental/DHC/EnergyTransferStations/Combined/Generation5/Examples/package.mo, Buildings/Experimental/DHC/EnergyTransferStations/Combined/Generation5/Validation/package.mo, Buildings/Experimental/DHC/Loads/Controls/Validation/package.mo, Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/UACp.mo, Buildings/ThermalZones/EnergyPlus/OutputVariable.mo, Buildings/ThermalZones/EnergyPlus/Validation/OutputVariable/OneZoneOneOutputVariableSummer.mo
=> Issue2421 broken links

Buildings/ThermalZones/EnergyPlus/Examples/SingleFamilyHouse/ShadeControl.mo
This updates the documentation for a Spawn model.
=> Updated documentation and deleted non-used instance

Buildings/Fluid/Sources/BaseClasses/PartialSource.mo
=> Correct missplaced each in PartialSource

Buildings/Electrical/AC/ThreePhasesUnbalanced/Validation/IEEETests/Test4NodesFeeder/BalancedStepDown/DY.mo, Buildings/Electrical/AC/ThreePhasesUnbalanced/Validation/IEEETests/Test4NodesFeeder/BalancedStepUp/YD.mo
=> Removed start value on load1.v

Buildings/Applications/DataCenters/DXCooled/Examples/DXCooledAirsideEconomizer.mo, Buildings/Fluid/Geothermal/Borefields/Examples/Borefields.mo, Buildings/Fluid/Geothermal/Borefields/Validation/ConstantHeatInjection_100Boreholes.mo, Buildings/Fluid/Geothermal/Borefields/Validation/Sandbox.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/MultiStage.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/SingleSpeed.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/SpaceCooling.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/VariableSpeed.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Validation/SingleSpeedEnergyPlus.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Validation/SingleSpeedPLREnergyPlus.mo, Buildings/Fluid/HeatExchangers/DXCoils/WaterCooled/Examples/MultiStage.mo, Buildings/Fluid/HeatExchangers/DXCoils/WaterCooled/Examples/SingleSpeed.mo, Buildings/Fluid/HeatExchangers/DXCoils/WaterCooled/Examples/VariableSpeed.mo, Buildings/Fluid/HeatExchangers/DXCoils/WaterCooled/Validation/VariableSpeedEnergyPlus.mo, Buildings/Fluid/HeatExchangers/DXCoils/WaterCooled/Validation/VariableSpeedEnergyPlusPartLoad.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/2439
=> Add missing parameters to record instantiations

Buildings/Fluid/Geothermal/Borefields/BaseClasses/PartialBorefield.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/PerformanceCurves/Curve_I.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/PerformanceCurves/Curve_II.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/PerformanceCurves/Curve_III.mo, Buildings/Fluid/Storage/BaseClasses/IndirectTankHeatExchanger.mo, Buildings/Utilities/IO/BCVTB/BaseClasses/FluidInterface.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/2440
=> Correct placement of each (master branch)

Buildings/Fluid/Geothermal/Borefields/BaseClasses/PartialBorefield.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/PerformanceCurves/Curve_I.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/PerformanceCurves/Curve_II.mo, Buildings/Fluid/HeatExchangers/DXCoils/AirCooled/Examples/PerformanceCurves/Curve_III.mo, Buildings/Fluid/Storage/BaseClasses/IndirectTankHeatExchanger.mo, Buildings/Utilities/IO/BCVTB/BaseClasses/FluidInterface.mo
This integrates https://github.com/lbl-srg/modelica-buildings/pull/2440
in the maintenance branch.
=> Correct placement of each (maintenance 7.0.x branch)

Buildings/Examples/VAVReheat/BaseClasses/VAVReheatBox.mo
This removes a connector to itself.
=> Removed connector to itself

Buildings/Fluid/HeatExchangers/BaseClasses/PartialPrescribedOutlet.mo, Buildings/Fluid/Interfaces/PrescribedOutlet.mo
This removes a duplicate declaration of m_flow_nominal
=> Removed duplicate declaration of m_flow_nominal

Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600FF.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases9xx/Case950FF.mo
This is for minor cleanup of the BESTEST models that does not affect the results.
=> Cleaned up component layout and added missing comments

Buildings/Fluid/CHPs/BaseClasses/EnergyConversionNormal.mo, Buildings/Fluid/CHPs/ThermalElectricalFollowing.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600FF.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case650FF.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases9xx/Case900FF.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases9xx/Case950FF.mo
This integrates #2471 into v7.0.x maintenance
=> Changed constraining type.

Buildings/Experimental/DHC/Examples/Combined/Generation5/Examples/BaseClasses/package.mo, Buildings/Experimental/DHC/Examples/Combined/Generation5/Examples/package.mo, Buildings/Experimental/DHC/Examples/Combined/Generation5/Loads/BaseClasses/package.mo, Buildings/Experimental/DHC/Networks/Controls.mo
=> Corrected hyperlinks for #2479

Buildings/Resources/bin/spawn-linux64/README.md, Buildings/Resources/bin/spawn-win64/README.md, Buildings/ThermalZones/EnergyPlus/UsersGuide.mo
=> Issue2491 spawn documentation

Buildings/Fluid/HeatPumps/Compressors/BaseClasses/PartialCompressor.mo
=> fix enthalpy typo

Buildings/Fluid/HeatPumps/Compressors/BaseClasses/PartialCompressor.mo, Buildings/Utilities/Psychrometrics/Functions/BaseClasses/der_saturationPressureLiquid.mo, Buildings/Utilities/Psychrometrics/Functions/BaseClasses/der_sublimationPressureIce.mo, Buildings/package.mo, README.md
=> Maint 7.0.x release notes

Buildings/Resources/Library/win64/ModelicaBuildingsEnergyPlus.dll, Buildings/package.mo, CMakeLists.txt
=> Include 7.0.1 release notes for 8.0.0 release

Buildings/ThermalZones/Detailed/BaseClasses/RadiationTemperature.mo, Buildings/package.mo
=> Corrected annotation for #2550

Buildings/ThermalZones/Detailed/Constructions/Examples/ExteriorWallTwoWindows.mo, Buildings/ThermalZones/Detailed/Constructions/Examples/ExteriorWallWithWindow.mo, Buildings/ThermalZones/Detailed/FLEXLAB/Rooms/X3B/Electrical.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600FF.mo
=> Fixed undeclared parameters

Buildings/ThermalZones/Detailed/Examples/Controls/package.mo, Buildings/ThermalZones/Detailed/Types.mo
=> Added missing extends statements for icons

Buildings/Resources/C-Sources/EnergyPlusWrapper.c, Buildings/Resources/C-Sources/EnergyPlusWrapper.h, Buildings/Resources/C-Sources/cfdExchangeData.c, Buildings/Resources/C-Sources/cfdcosim.c, Buildings/Resources/C-Sources/cryptographicsHash.c, Buildings/Resources/C-Sources/exchangeValues.c, Buildings/Resources/C-Sources/externalObjectStructure.h, Buildings/Resources/C-Sources/getTimeSpan.c, Buildings/Resources/C-Sources/initArray.c, Buildings/Resources/C-Sources/plotFree.c, Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/C-Sources/plotSendReal.c, Buildings/Resources/C-Sources/plotSendString.c, Buildings/Resources/C-Sources/plotSendTerminalString.c, Buildings/Resources/C-Sources/pythonWrapper.c
This implements changes from IBPSA, #1507
=> Removed include statement 

Buildings/Resources/C-Sources/EnergyPlusWrapper.c, Buildings/Resources/C-Sources/EnergyPlusWrapper.h, Buildings/Resources/C-Sources/cfdExchangeData.c, Buildings/Resources/C-Sources/cfdcosim.c, Buildings/Resources/C-Sources/cryptographicsHash.c, Buildings/Resources/C-Sources/exchangeValues.c, Buildings/Resources/C-Sources/externalObjectStructure.h, Buildings/Resources/C-Sources/getTimeSpan.c, Buildings/Resources/C-Sources/initArray.c, Buildings/Resources/C-Sources/plotFree.c, Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/C-Sources/plotSendReal.c, Buildings/Resources/C-Sources/plotSendString.c, Buildings/Resources/C-Sources/plotSendTerminalString.c, Buildings/Resources/C-Sources/pythonWrapper.c, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/SpawnFMU.h
This merges the changes from IBPSA, issue 1507
=> Remove include statement of ModelicaUtilities.h on 8.0.x branch

Buildings/Resources/C-Sources/cfdExchangeData.c, Buildings/Resources/C-Sources/cfdcosim.c, Buildings/Resources/C-Sources/cryptographicsHash.c, Buildings/Resources/C-Sources/exchangeValues.c, Buildings/Resources/C-Sources/externalObjectStructure.h, Buildings/Resources/C-Sources/getTimeSpan.c, Buildings/Resources/C-Sources/initArray.c, Buildings/Resources/C-Sources/plotFree.c, Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/C-Sources/plotSendReal.c, Buildings/Resources/C-Sources/plotSendString.c, Buildings/Resources/C-Sources/plotSendTerminalString.c, Buildings/Resources/C-Sources/pythonWrapper.c
This merges the changes from IBPSA, issue 1507
=> Remove include statement of ModelicaUtilities.h on 7.0.x branch

Buildings/Examples/VAVReheat/ASHRAE2006.mo, Buildings/Examples/VAVReheat/BaseClasses/Floor.mo, Buildings/Examples/VAVReheat/BaseClasses/PartialOpenLoop.mo, Buildings/Examples/VAVReheat/Guideline36.mo, Buildings/ThermalZones/EnergyPlus/Examples/SmallOffice/ASHRAE2006Winter.mo, Buildings/ThermalZones/EnergyPlus/Examples/SmallOffice/BaseClasses/Floor.mo, Buildings/ThermalZones/EnergyPlus/Examples/SmallOffice/Guideline36Winter.mo
=> Updated documentation for #2600

.github/workflows/formatting.yml, .travis.yml
This should correct the error in https://github.com/lbl-srg/modelica-buildings/runs/3537594704?check_suite_focus=true
=> Removed setuptools from pip3

.github/workflows/formatting.yml, .travis.yml, Buildings/package.mo
This adds release notes for version 8.0.1
=> Added release notes for 8.0.1

Buildings/Controls/OBC/CDL/Interfaces/BooleanInput.mo, Buildings/Controls/OBC/CDL/Interfaces/BooleanOutput.mo, Buildings/Controls/OBC/CDL/Interfaces/IntegerInput.mo, Buildings/Controls/OBC/CDL/Interfaces/IntegerOutput.mo, Buildings/Controls/OBC/CDL/Interfaces/RealInput.mo, Buildings/Controls/OBC/CDL/Interfaces/RealOutput.mo
=> removed single quote in class comments

Buildings/BoundaryConditions/SolarGeometry/BaseClasses/SolarAzimuth.mo, Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/Examples/BrighteningCoefficient.mo, Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/Examples/RelativeAirMass.mo, Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/Examples/SkyBrightness.mo, Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/RelativeAirMass.mo, Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/SkyBrightness.mo, Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/SkyClearness.mo, Buildings/BoundaryConditions/SolarIrradiation/DiffusePerez.mo
This merges IBPSA, issue1477_diffuseRadiation_AND_issue1478_BESTEST_weatherfiles
=> Added changes to connector location and documentation

Buildings/package.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/2622
=> Correct links in revision notes

Buildings/ThermalZones/Detailed/BaseClasses/CFDSurfaceIdentifier.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/2618
=> Remove parameter prefix

Buildings/ThermalZones/Detailed/BaseClasses/CFDSurfaceIdentifier.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/2619
=> Remove parameter prefix for maint_8.0.x

Buildings/ThermalZones/Detailed/BaseClasses/CFDSurfaceIdentifier.mo
This integrates https://github.com/lbl-srg/modelica-buildings/pull/2620
=> Removed parameter prefix for maint_7.0.x

Buildings/Experimental/DHC/CentralPlants/BaseClasses/PartialPlant.mo
=> Corrected if expressions

Buildings/Applications/DataCenters/ChillerCooled/Examples/BaseClasses/PartialDataCenter.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimaryLoadSideEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimarySecondaryEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/NonIntegratedPrimarySecondaryEconomizer.mo, Buildings/package.mo
=> Correct weather data bus connection (7.0.x)

Buildings/Fluid/HeatExchangers/WetCoilEffectivenessNTU.mo
=> Corrected units in WetCoilEffectivenessNTU (8.0.x)

Buildings/Applications/DataCenters/ChillerCooled/Equipment/BaseClasses/PartialIntegratedPrimary.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/BaseClasses/PartialDataCenter.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimaryLoadSideEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimarySecondaryEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/NonIntegratedPrimarySecondaryEconomizer.mo, Buildings/Experimental/DHC/EnergyTransferStations/BaseClasses/computeCoordinates.mo, Buildings/HeatTransfer/Windows/BaseClasses/RadiationBaseData.mo, Buildings/HeatTransfer/Windows/BaseClasses/convectionHorizontalCavity.mo, Buildings/HeatTransfer/Windows/BaseClasses/convectionVerticalCavity.mo, Buildings/HeatTransfer/Windows/BaseClasses/nusseltHorizontalCavityEnhanced.mo, Buildings/HeatTransfer/Windows/BaseClasses/nusseltHorizontalCavityReduced.mo, Buildings/HeatTransfer/Windows/BaseClasses/smoothInterpolation.mo, Buildings/package.mo
=> Issue2706 data center weather bus

Buildings/Fluid/HeatExchangers/WetCoilEffectivenessNTU.mo
=> Corrected units for WetCoilEffectivenessNTU (master)

Buildings/Applications/DataCenters/ChillerCooled/Examples/BaseClasses/PartialDataCenter.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimaryLoadSideEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/IntegratedPrimarySecondaryEconomizer.mo, Buildings/Applications/DataCenters/ChillerCooled/Examples/NonIntegratedPrimarySecondaryEconomizer.mo, Buildings/package.mo
=> Correct weather data bus connection (8.0.x)

Buildings/Resources/C-Sources/EnergyPlusWrapper.h
=> Added ModelicaUtilities.h for Spawn

Buildings/ThermalZones/Detailed/BaseClasses/CFDThread.mo, Buildings/ThermalZones/Detailed/BaseClasses/ConstructionNumbers.mo, Buildings/ThermalZones/Detailed/BaseClasses/ConstructionRecords.mo, Buildings/ThermalZones/Detailed/BaseClasses/ExteriorBoundaryConditionsWithWindow.mo, Buildings/ThermalZones/Detailed/BaseClasses/RoomHeatMassBalance.mo, Buildings/ThermalZones/Detailed/BaseClasses/cfdExchangeData.mo, Buildings/ThermalZones/Detailed/BaseClasses/cfdStartCosimulation.mo
This closes #2731 
It also adds icon information and removes a `visible` keyword that depends on a function evaluation.
=> Correct use of each keyword

Buildings/ThermalZones/Detailed/BaseClasses/CFDThread.mo, Buildings/ThermalZones/Detailed/BaseClasses/ConstructionNumbers.mo, Buildings/ThermalZones/Detailed/BaseClasses/ConstructionRecords.mo, Buildings/ThermalZones/Detailed/BaseClasses/ExteriorBoundaryConditionsWithWindow.mo, Buildings/ThermalZones/Detailed/BaseClasses/RoomHeatMassBalance.mo, Buildings/ThermalZones/Detailed/BaseClasses/cfdExchangeData.mo, Buildings/ThermalZones/Detailed/BaseClasses/cfdStartCosimulation.mo
=> Corrected each keyword and icons (7.0.x)

Buildings/ThermalZones/Detailed/BaseClasses/CFDThread.mo, Buildings/ThermalZones/Detailed/BaseClasses/ConstructionNumbers.mo, Buildings/ThermalZones/Detailed/BaseClasses/ConstructionRecords.mo, Buildings/ThermalZones/Detailed/BaseClasses/ExteriorBoundaryConditionsWithWindow.mo, Buildings/ThermalZones/Detailed/BaseClasses/RoomHeatMassBalance.mo, Buildings/ThermalZones/Detailed/BaseClasses/cfdExchangeData.mo, Buildings/ThermalZones/Detailed/BaseClasses/cfdStartCosimulation.mo
=> Corrected each keyword (8.0.x)

Buildings/Fluid/MixingVolumes/BaseClasses/MixingVolumeHeatMoisturePort.mo, Buildings/Fluid/MixingVolumes/BaseClasses/MixingVolumeHeatPort.mo
This corrects a typo in the annotation keyword.
=> Correct defaultComponentName annotation

Buildings/Fluid/MixingVolumes/BaseClasses/MixingVolumeHeatMoisturePort.mo, Buildings/Fluid/MixingVolumes/BaseClasses/MixingVolumeHeatPort.mo
This corrects a typo in an annotation keyword.
=> Corrected defaultComponentName annotation (8.0.x)

Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilDryRegime.mo, Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilDryWetRegime.mo, Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilUARated.mo, Buildings/Fluid/HeatExchangers/Validation/WetCoilEffectivenessNTU.mo, Buildings/Fluid/HeatExchangers/Validation/WetCoilEffectivenessNTUHeating.mo
=> Fix documentation and typos, use URI

Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilDryRegime.mo, Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilDryWetRegime.mo, Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilUARated.mo, Buildings/Fluid/HeatExchangers/Validation/WetCoilEffectivenessNTU.mo, Buildings/Fluid/HeatExchangers/Validation/WetCoilEffectivenessNTUHeating.mo
This integrates https://github.com/lbl-srg/modelica-buildings/pull/2745 into the 8.0.x maintenance branch.
=> Fix documentation and typos, use URI (8.0.x)

Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Reheat/SystemRequests.mo
This closes https://github.com/lbl-srg/modelica-buildings/pull/2729
@JayHuLBL : The changes look good. Please make sure you make them also for the final release of Guideline 36.
=> Karthikeyad pnnl issue2728 g36 terminal add supply request output

Buildings/Examples/ChillerPlant/BaseClasses/DataCenter.mo, Buildings/package.mo
This integrates changes from #2766
=> Remove warnings in data center models (7.0.x)

Buildings/Resources/Data/BoundaryConditions/Validation/BESTEST/generateResults.py
This removes the call to unload MSL. This is needed for https://github.com/lbl-srg/BuildingsPy/pull/437
=> Removed unloading of MSL (8.0.x)

.travis.yml, Buildings/Resources/Data/BoundaryConditions/Validation/BESTEST/generateResults.py
This is for testing only, don't merge.
=> Removed unloading of MSL

Buildings/Fluid/Examples/Performance/PressureDrop/ParallelDpOptimised.mo, Buildings/Resources/Data/BoundaryConditions/Validation/BESTEST/generateResults.py
This merges IBPSA, issue1556_filePermissions
=> Merged IBPSA, issue1556_filePermissions

.travis.yml, Buildings/Resources/Data/BoundaryConditions/Validation/BESTEST/generateResults.py, Buildings/Resources/Scripts/travis/Makefile
This integrates https://github.com/lbl-srg/BuildingsPy/issues/441 to skip some translation statistics
=> Skip verification of certain translation statistics

.travis.yml
Updated BuildingsPy to current master.
=> Updated BUILDINGSPY_VERSION=BuildingsPy@1783a1e

.travis.yml
=> Updated to BUILDINGSPY_VERSION=BuildingsPy@5a133c8

Buildings/package.mo
This updates the release information on the `master`.
=> Copied release information from 7.0.2 and 8.1.0

Buildings/package.mo
This adds a new table to log upcoming changes to the `maint_8.1.x` branch.
=> Add 8.1.1 release information template

Buildings/package.mo
This adds the template for the changes for version 7.0.x
=> Updated version information for 7.0.x branch

.github/workflows/formatting.yml, .travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Changed to dassl as the default for OpenModelica CI tests

Buildings/Experimental/DHC/Loads/BaseClasses/getPeakLoad.mo, Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Refactored getPeakLoad.mo

Buildings/Fluid/HeatExchangers/CoolingTowers/BaseClasses/CoolingTower.mo, Buildings/Fluid/HeatExchangers/CoolingTowers/BaseClasses/CoolingTowerVariableSpeed.mo, Buildings/Fluid/HeatExchangers/CoolingTowers/Merkel.mo, Buildings/Fluid/HeatExchangers/CoolingTowers/YorkCalc.mo
This correct graphical layout and adds the current value of the outlet water temperature
=> Corrected icons of cooling towers

Buildings/Fluid/Storage/Ice/Tank.mo
=> issue2874 ice tank BOM

.travis.yml, Buildings/BoundaryConditions/GroundTemperature/ClimaticConstants.mo, Buildings/Fluid/Geothermal/BuriedPipes/Validation/GroundCouplingAIT.mo, Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Issue2887 open modelica image

Buildings/Examples/Tutorial/Boiler/System7.mo, Buildings/Resources/Scripts/Dymola/Examples/Tutorial/Boiler/System7.mos, Buildings/package.mo
This corrects the logic that switches the system off.
=> Patch tutorial boiler system7

Buildings/ThermalZones/EnergyPlus/Examples/SmallOffice/BaseClasses/Floor.mo
This removes a non-needed assertion.
=> Removed non-needed assertion on opeWesCor.wOpe

Buildings/Controls/OBC/CDL/Integers/Subtract.mo
=> corrected output connector

Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/partialInternalResistances.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalHEXOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalHEXTwoUTube.mo
This removes the print statements in the borehole functions, which made the functions impure.
=> Merges IBPSA, issue 1584

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml
This updates the OpenModelica image to the latest daily built, and enables more tests.
=> Update OpenModelica image

.travis.yml, Buildings/Resources/C-Sources/cfdExchangeData.c, Buildings/Resources/C-Sources/cfdSendStopCommand.c, Buildings/Resources/C-Sources/cfdStartCosimulation.c, Buildings/Resources/C-Sources/cfdcosim.c, Buildings/Resources/C-Sources/exchangeValues.c, Buildings/Resources/C-Sources/fileWriterFree.c, Buildings/Resources/C-Sources/fileWriterInit.c, Buildings/Resources/C-Sources/fileWriterStructure.c, Buildings/Resources/C-Sources/getTimeSpan.c, Buildings/Resources/C-Sources/initArray.c, Buildings/Resources/C-Sources/jsonWriterInit.c, Buildings/Resources/C-Sources/plotFree.c, Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/C-Sources/plotSendString.c, Buildings/Resources/C-Sources/plotSendTerminalString.c, Buildings/Resources/C-Sources/pythonWrapper.c, Buildings/Resources/Scripts/BuildingsPy/conf.json, Buildings/Resources/Scripts/travis/optimica/jm_ipython.sh
This ports https://github.com/lbl-srg/modelica-buildings/pull/2929 to the 8.1.x maintenance branch
=> This add missing include directives for the 8.1.x maintenance branch

Buildings/Resources/C-Sources/EnergyPlusWrapper.c
This integrates https://github.com/lbl-srg/modelica-buildings/pull/2937 in the maintenance branch
=> Maintance 8.1.x - Changed char** to const char**

Buildings/Media/Specialized/Water/TemperatureDependentDensity.mo, Buildings/package.mo
This is for IBPSA, 1603
It does not affect the results because the medium is a liquid.
=> Corrected unit error in gas constant

Buildings/Media/Specialized/Water/TemperatureDependentDensity.mo, Buildings/package.mo
This does not affect the results as the medium is a liquid.
=> Correct unit error in assignment of gas constant

Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/IntegratedPrimaryLoadSide.mo, Buildings/package.mo
=> Removed duplicate model instance

Buildings/Applications/DataCenters/ChillerCooled/Equipment/Validation/IntegratedPrimaryLoadSide.mo, Buildings/package.mo
=> Maint 8.1.x - Removed duplicate model instance 

Buildings/Electrical/AC/OnePhase/Conversion/ACACConverter.mo, Buildings/Electrical/AC/OnePhase/Conversion/ACDCConverter.mo, Buildings/Electrical/AC/OnePhase/Sources/Generator.mo, Buildings/Electrical/UsersGuide.mo, Buildings/Fluid/Storage/Ice/BaseClasses/NormalizedHeatFlowRate.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/UsersGuide.mo, Buildings/Utilities/Time/ModelTime.mo
=> Issue2960 correct hyperlinks

Buildings/Fluid/Storage/Ice/Tank.mo
=> removed BOM

Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_8_to_9.0.0.mos
This corrects wrong use of `convertClass`
=> Corrected conversion script entries

Buildings/Controls/OBC/CDL/Continuous/PID.mo, Buildings/Controls/OBC/CDL/Continuous/PIDWithReset.mo, Buildings/package.mo
=> Corrected documentation of derivative approximation (maint 8.1)

Buildings/Controls/OBC/CDL/Continuous/PID.mo, Buildings/Controls/OBC/CDL/Continuous/PIDWithReset.mo, Buildings/package.mo
=> Corrected documentation of derivative approximation

.travis.yml, Buildings/Resources/Scripts/travis/dymola/dymola
This updates the docker image that has uses the updated license file
=> Updated Dymola license file

Buildings/package.mo
This updates the release notes for future development of the 8.1.x maintenance branch.
=> Updated release notes for 8.1.2 development

Buildings/Controls/OBC/CDL/Continuous/Divide.mo, Buildings/Controls/OBC/CDL/Continuous/Greater.mo, Buildings/Controls/OBC/CDL/Continuous/GreaterThreshold.mo, Buildings/Controls/OBC/CDL/Continuous/Less.mo, Buildings/Controls/OBC/CDL/Continuous/LessThreshold.mo, Buildings/Controls/OBC/CDL/Continuous/Sort.mo, Buildings/Controls/OBC/CDL/Discrete/TriggeredMax.mo, Buildings/Controls/OBC/CDL/Discrete/TriggeredSampler.mo
This change lists all inputs before all outputs
=> Changed order of instantiation

Buildings/Fluid/HeatPumps/Data/EquationFitReversible/BaseClasses/HeatingCoolingData.mo, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/BaseClasses/package.mo, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/BaseClasses/package.order, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/Generic.mo, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/package.order, Buildings/package.mo
=> Remove protected record declaration inside record

Buildings/Fluid/HeatPumps/Data/EquationFitReversible/BaseClasses/HeatingCoolingData.mo, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/BaseClasses/package.mo, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/BaseClasses/package.order, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/Generic.mo, Buildings/Fluid/HeatPumps/Data/EquationFitReversible/package.order, Buildings/package.mo
=> Removed protected declaration in record (maint 8.1.x)

.github/workflows/formatting.yml, .travis.yml
This updates BuildingsPy to the latest release
=> Update CI testing to BuildingsPy 4.0.0

Buildings/Controls/OBC/CDL/Conversions/BooleanToInteger.mo, Buildings/Controls/OBC/CDL/Conversions/BooleanToReal.mo, Buildings/Controls/OBC/CDL/Conversions/Validation/BooleanToInteger.mo, Buildings/Controls/OBC/CDL/Conversions/Validation/BooleanToReal.mo, Buildings/Controls/OBC/CDL/Conversions/Validation/IntegerToReal.mo, Buildings/package.mo
This PR merges changes made in #3017 that are under `OBC` to `maint_8.1.x`.
=> Maint 8.1.x issue3016 text and graphic errors

Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus_9_6_0.so, Buildings/Resources/Library/win64/ModelicaBuildingsEnergyPlus_9_6_0.dll, Buildings/Resources/Scripts/travis/pyfmi/runSpawnFromOtherDirectory.py, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/BuildingInstantiate.c, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/SpawnFMU.c, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/SpawnObjectFree.c, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/SpawnTypes.h, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/SpawnUtil.c, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/install.py, Buildings/ThermalZones/EnergyPlus_9_6_0/Building.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/UsersGuide.mo
=> Issue2852 spawn multiplier

Buildings/HeatTransfer/Windows/BaseClasses/CenterOfGlass.mo, Buildings/package.mo
=> Changed gas layer to be conditional

Buildings/package.mo
This updates the release information for development after the 9.0.0 release.
=> Added release notes for post 9.0.0 development

Buildings/Examples/HydronicHeating/TwoRoomsWithStorage.mo, Buildings/package.mo
=> Corrected temperature at which heating switches on

Buildings/HeatTransfer/Windows/Functions/glassTRExteriorIrradiationNoShading.mo, Buildings/HeatTransfer/Windows/Functions/glassTRInteriorIrradiationNoShading.mo, Buildings/package.mo
=> added the default values

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml, Buildings/Resources/Scripts/travis/Makefile, Buildings/Resources/Scripts/travis/omc/omc
=> Issue3104 openmodelica v2

Buildings/Utilities/Math/Functions/regNonZeroPower.mo, Buildings/Utilities/Math/RegNonZeroPower.mo, Buildings/package.mo
This merges https://github.com/lbl-srg/modelica-buildings/pull/3142 that improves `regNonZerPow`
=> Maint 8.1.x patch reg non zero pow

Buildings/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo, Buildings/package.mo
=> Corrected temperature in assignment of sta2_default

Buildings/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo, Buildings/package.mo
Corrected assignment of sta2_default
=> Maint 9.0.x partial effectiveness ntu

Buildings/Utilities/IO/Python_3_8/UsersGuide.mo
=> added the tested  minor python version

Buildings/Controls/OBC/Utilities/PIDWithAutotuning/AutoTuner/AMIGO/PI.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/AutoTuner/AMIGO/PID.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/AutoTuner/AMIGO/PIDDerivativeTime.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/AutoTuner/AMIGO/PIDGain.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/AutoTuner/AMIGO/PIDIntegralTime.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/AutoTuner/AMIGO/PIGain.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/AutoTuner/AMIGO/PIIntegralTime.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/Relay/HalfPeriodRatio.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/Relay/OnOffPeriod.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/Relay/ResponseProcess.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/ControlProcessModel.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/Gain.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/TimeConstantDelay.mo
@JayHuLBL Could you please take a look at the minor changes below? I added unit to the time-related inputs based on Michael's earlier comments
=> Issue2884 pid autotuning

Buildings/ThermalZones/EnergyPlus_9_6_0/UsersGuide.mo
Removed link to issue that has been corrected
=> Update Spawn user guide (maint 9.1.x)

Buildings/ThermalZones/EnergyPlus_9_6_0/OpaqueConstruction.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/UsersGuide.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/ZoneSurface.mo
Removed link to issue that has been corrected
=> Update Spawn user guide

Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
This is for https://github.com/lbl-srg/modelica-buildings/pull/3191
=> Updated version of certifi

Buildings/Fluid/Sensors/BaseClasses/PartialDynamicFlowSensor.mo, Buildings/HeatTransfer/Data/BaseClasses.mo
See also https://github.com/ibpsa/modelica-ibpsa/pull/1673
=> Merged IBPSA, avoided comparison for equality

Buildings/Utilities/Time/CalendarTime.mo, Buildings/package.mo
=> Issue3199 calendar time (master)

Buildings/Utilities/Time/CalendarTime.mo, Buildings/package.mo
This integrates the bug fix for #3199
=> Refactored sampling to avoid rounding errors in CalendarTime (maint_8.1.x)

Buildings/Fluid/Storage/Examples/ExpansionVessel.mo
This closes #3198.
@mwetter 
I will make the PR for `maint_9.1.x` as well as the IBPSA library once you approve of the changes.
=> Issue3198 expansion vessel old documentation

Buildings/Fluid/Storage/Examples/ExpansionVessel.mo
This PR merges changes made in #3198 to `maint_9.1.x`.
=> Maint 9.1.x issue3198 expansion vessel old documentation

Buildings/Fluid/Sources/BaseClasses/Outside.mo, Buildings/Fluid/Sources/BaseClasses/PartialAirSource.mo, Buildings/Fluid/Sources/BaseClasses/package.order, Buildings/Fluid/Sources/MassFlowSource_WeatherData.mo, Buildings/package.mo
This closes #3215.
This pull request merges the changes in [IBPSA PR #1681](https://github.com/ibpsa/modelica-ibpsa/pull/1686).
=> added new baseclass, updated release note

Buildings/Electrical/Interfaces/PartialTwoPort.mo, Buildings/package.mo
This closes #3236 
@LauraMaier: This also needs to be added to the port in the IBPSA library.
=> Issue3236 electrical component access

Buildings/Electrical/Interfaces/PartialTwoPort.mo, Buildings/package.mo
=> Added constraining clause

.travis.yml, Buildings/Electrical/Interfaces/PartialTwoPort.mo, Buildings/Resources/Scripts/BuildingsPy/conf.yml, Buildings/package.mo
=> Update optimica to version 1.40

Buildings/Fluid/Actuators/Valves/ThreeWayEqualPercentageLinear.mo, Buildings/Fluid/Actuators/Valves/ThreeWayLinear.mo, Buildings/Fluid/Actuators/Valves/ThreeWayTable.mo, Buildings/Fluid/HeatPumps/BaseClasses/PartialWaterToWater.mo, Buildings/Media/Steam.mo, Buildings/Obsolete/Fluid/Sources/FixedBoundary.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/Examples/SmallOffice/BaseClasses/Floor.mo
This closes #3243.
@mwetter - I will merge relevant files to IBPSA once you approve these changes.
=> Issue3243 misc fixes

Buildings/Controls/OBC/CDL/Psychrometrics/WetBulb_TDryBulPhi.mo, Buildings/Fluid/Examples/Performance/Example5.mo, Buildings/Fluid/Examples/Performance/Example6.mo, Buildings/Fluid/Examples/Performance/Example7.mo, Buildings/Fluid/Examples/Performance/Example8.mo, Buildings/Fluid/HeatExchangers/BaseClasses/Examples/EpsilonNTUZ.mo, Buildings/Utilities/Plotters/Examples/Scatter.mo, Buildings/Utilities/Plotters/Examples/TimeSeries.mo, Buildings/Utilities/Psychrometrics/TWetBul_TDryBulPhi.mo, Buildings/Utilities/Psychrometrics/TWetBul_TDryBulXi.mo
=> Added a constant in order for unit check to pass

Buildings/Controls/OBC/CDL/Psychrometrics/WetBulb_TDryBulPhi.mo, Buildings/Fluid/Examples/Performance/Example5.mo, Buildings/Fluid/Examples/Performance/Example6.mo, Buildings/Fluid/Examples/Performance/Example7.mo, Buildings/Fluid/Examples/Performance/Example8.mo, Buildings/Fluid/HeatExchangers/BaseClasses/Examples/EpsilonNTUZ.mo, Buildings/Utilities/Plotters/Examples/Scatter.mo, Buildings/Utilities/Plotters/Examples/TimeSeries.mo, Buildings/Utilities/Psychrometrics/TWetBul_TDryBulPhi.mo, Buildings/Utilities/Psychrometrics/TWetBul_TDryBulXi.mo, Buildings/package.mo
This is needed for Dymola 2023x refresh1, beta1
=> Updated models so that unit test passes (maint 9.1.x)

Buildings/Resources/C-Sources/cfdExchangeData.c, Buildings/Resources/src/FastFluidDynamics/sci_reader.c
This PR includes the changes in the PR #3272 and #3273.
=> included changes from PR #3272 and #3273

Buildings/Controls/OBC/CDL/Continuous/Acos.mo, Buildings/Controls/OBC/CDL/Continuous/Asin.mo, Buildings/Controls/OBC/CDL/Continuous/Atan.mo, Buildings/Controls/OBC/CDL/Continuous/Atan2.mo, Buildings/Controls/OBC/CDL/Continuous/Cos.mo, Buildings/Controls/OBC/CDL/Continuous/Sin.mo, Buildings/Controls/OBC/CDL/Continuous/Tan.mo, Buildings/Controls/OBC/CDL/Continuous/Validation/Derivative.mo, Buildings/package.mo
=> added units to the input and output of the trigonometric functions

Buildings/Controls/OBC/Utilities/PIDWithAutotuning/Relay/Controller.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/Relay/HalfPeriodRatio.mo
This is to fix  https://github.com/lbl-srg/modelica-buildings/pull/2957#discussion_r1131764356
=> issue2884 update model doc

Buildings/Controls/OBC/ASHRAE/G36/package.mo, Buildings/Controls/OBC/CDL/Continuous/Validation/MovingAverage.mo, Buildings/Controls/OBC/CDL/Utilities/Validation/SunRiseSet.mo, Buildings/Controls/OBC/CDL/Utilities/Validation/SunRiseSetNegativeStartTime.mo, Buildings/Controls/OBC/CDL/Utilities/Validation/SunRiseSetPositiveStartTime.mo, Buildings/Controls/OBC/CDL/package.mo, Buildings/Obsolete/Controls/OBC/ASHRAE/G36_PR1/package.mo, Buildings/package.mo, bin/cleanHTML.py
=> Issue3301 cdl conformance

Buildings/Controls/OBC/CDL/Continuous/Validation/MovingAverage.mo, Buildings/Controls/OBC/CDL/Utilities/Validation/SunRiseSet.mo, Buildings/Controls/OBC/CDL/Utilities/Validation/SunRiseSetNegativeStartTime.mo, Buildings/Controls/OBC/CDL/Utilities/Validation/SunRiseSetPositiveStartTime.mo, Buildings/package.mo, bin/cleanHTML.py
=> Changed models to be compliant with CDL (maint 9.1.x)

.travis.yml
=> Updated oct license file

Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/Evaporation.mo, Buildings/package.mo
It adds the changes to address #3322.
=> Corrected assertion, added release note

Buildings/Controls/OBC/CDL/Logical/Latch.mo, Buildings/Controls/OBC/CDL/Logical/Pre.mo, Buildings/Controls/OBC/CDL/Logical/Toggle.mo
=> corrected wrong variable names graphical annotation

Buildings/Controls/OBC/CDL/Logical/Latch.mo, Buildings/Controls/OBC/CDL/Logical/Pre.mo, Buildings/Controls/OBC/CDL/Logical/Toggle.mo
This contains changes in PR #3331.
=> corrected variable names in graphical annotation

Buildings/Fluid/Movers/BaseClasses/FlowMachineInterface.mo, Buildings/Fluid/Movers/BaseClasses/PartialFlowMachine.mo, Buildings/Fluid/Movers/Data/Generic.mo
Reduces length of assertion message, sets dpMax and V_flow_max final
=> Update Movers from IBPSA

Buildings/Examples/ScalableBenchmarks/BuildingVAV/Examples/OneFloor_OneZone.mo, Buildings/Fluid/HeatExchangers/BaseClasses/PartialEffectiveness.mo
This PR ports changes made for `Buildings/Fluid/HeatExchangers/BaseClasses/PartialEffectiveness.mo` from https://github.com/lbl-srg/modelica-buildings/pull/3361/files to the `maint_9.1.x` branch.
=> Maint 9.1.x issue3360 optimica

.travis.yml
This updates the dymola image with the new license file.
=> Updated dymola image with new license file.

.travis.yml
This updates the dymola license file.
=> Update Dymola license file (main 9.1.x)

Buildings/package.mo
=> issue3372 clean out Nrpm in release notes

Buildings/Media/Examples/BaseClasses/PartialProperties.mo, Buildings/package.mo
This PR syncs changes made in https://github.com/ibpsa/modelica-ibpsa/pull/1743.
This closes #3384.
=> Issue3384 self dependent binding

Buildings/Media/Examples/BaseClasses/PartialProperties.mo, Buildings/package.mo
This applies the same changes made in #3387 for `maint_9.1.x`.
=> Maint 9.1.x issue3384 self dependent binding

Buildings/Fluid/Boilers/BaseClasses/PartialBoiler.mo, Buildings/Fluid/Delays/DelayFirstOrder.mo, Buildings/package.mo
This PR is to merge changes made in #3392 that are applicable to `maint_9.1.x` to the maintenance branch.
=> Maint 9.1.x issue3391 documentation and release notes

Buildings/Resources/C-Sources/jsonWriterInit.c
See https://github.com/lbl-srg/modelica-buildings/issues/3382#issuecomment-1546721932
=> Corrected pointer

Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/CoilCapacityAirSource.mo, Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/CoolingCapacityWaterCooled.mo, Buildings/Fluid/HeatExchangers/DXCoils/BaseClasses/PartialWaterCooledDXCoil.mo
@mwetter Submitting this PR to resolve the errors we are seeing in CI testing for OpenModelica and Optimica. I have manually checked it for errors on OpenModelica after making the changes. I also updated the encoding in a couple of files that had BOM.
=> Issue3288 dx coil heating 052023

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/Scripts/BuildingsPy/conf.yml
This integrates the security alert from https://github.com/lbl-srg/modelica-buildings/pull/3407
=> Updated version of request to 2.31.0

Buildings/Experimental/DHC/Plants/Reservoir/BoreField.mo
This allows the record to be replaced by models that extend this model
=> Removed final modifier in borefield model

Buildings/Experimental/DHC/Examples/Combined/BaseClasses/PartialSeries.mo
This adds units so that the plot shows temperatures in degC.
=> Added units to instance conVio

Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/convectionResistanceCircularPipe.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/partialInternalResistances.mo, Buildings/package.mo
This integrates IBPSA 1762.
This corrects the variability as assigning an input to a parameter is not allowed
=> Corrected variability

Buildings/Controls/OBC/Utilities/PIDWithInputGains.mo, Buildings/package.mo
=> changed instance to conditional, added release note

Buildings/Controls/OBC/Utilities/PIDWithInputGains.mo, Buildings/package.mo
=> changed instance to be conditional, added revision note

Buildings/Controls/OBC/CDL/Continuous/IntegratorWithReset.mo
This improves the documentation
=> Updated info section of CDL.IntegratorWithReset

Buildings/Fluid/DXSystems/Cooling/AirSource/MultiStage.mo, Buildings/Fluid/DXSystems/Cooling/AirSource/SingleSpeed.mo, Buildings/Fluid/DXSystems/Cooling/AirSource/VariableSpeed.mo, Buildings/Fluid/DXSystems/Cooling/BaseClasses/PartialDXCoil.mo, Buildings/Fluid/DXSystems/Cooling/BaseClasses/PartialWaterCooledDXCoil.mo, Buildings/Fluid/DXSystems/Cooling/WaterSource/MultiStage.mo, Buildings/Fluid/DXSystems/Cooling/WaterSource/SingleSpeed.mo, Buildings/Fluid/DXSystems/Cooling/WaterSource/VariableSpeed.mo, Buildings/Fluid/DXSystems/Heating/AirSource/Examples/SingleSpeed.mo, Buildings/Fluid/DXSystems/Heating/AirSource/SingleSpeed.mo, Buildings/Fluid/DXSystems/Heating/AirSource/Validation/BaseClasses/SingleSpeedHeating.mo, Buildings/Fluid/DXSystems/Heating/BaseClasses/PartialDXHeatingCoil.mo
This updates the icons for the DXSystems
=> Updated DXSystems icons

Buildings/Fluid/FMI/Adaptors/Outlet.mo, Buildings/Utilities/Math/Functions/bicubic.mo
This merges the IBPSA bug fix for Fluid.FMI.Adaptors.Outlet
=> Merged IBPSA, issue 1668 (Fluid.FMI.Adaptors.Outlet)

Buildings/Fluid/FMI/Adaptors/Outlet.mo, Buildings/Utilities/Math/Functions/bicubic.mo, Buildings/package.mo
This corrects the dimension which caused the model to not translate in some tools if water is used (with nX=1).
=> Corrected dimension of X in Adaptors.Outlet

Buildings/Experimental/DHC/Examples/Cooling/ElectricChillersDirectETS.mo
This is needed for Dymola 2024x beta1 on Linux
=> Changed call to loadResources

Buildings/Resources/Scripts/EnergyPlus/energyplus_csv_to_mos.py
This closes #3484.
@JayHuLBL I am submitting this PR to add an extra argument to the Python script for generating DAT files in the MBL. This will be useful for the SPAWN-based validation we are introducing with the zonal HVAC system models. Thanks!
=> Issue3484 dat generation update

Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Increased timeout for Examples.AllElectricCWStorage

.travis.yml
This updates the BuildingsPy version.
=> Updated BuildingsPy to 5.0.0 release candidate

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml, Buildings/package.mo, README.md
=> Issue3497 release10 0 0 preparations

Buildings/package.mo
This updates the release notes.
=> Updated release notes (maint 9.1.x branch)

Buildings/package.mo
This adds the template for the release notes for 10.1.0. Depending on changes, this may be changed to 11.0.0 later.
=> Added release notes for 10.1.0

Buildings/package.mo
=> Added Saranya Anbarasu to contributor lists

Buildings/package.mo
=> Added Saranya Anbarasu to contributor list (10.0.x maint)

Buildings/Experimental/DHC/Examples/Steam/SingleBoiler.mo, Buildings/Experimental/DHC/Loads/Steam/BaseClasses/ControlVolumeCondensation.mo, Buildings/Experimental/DHC/Loads/Steam/BaseClasses/SteamTrap.mo, Buildings/Experimental/DHC/Loads/Steam/BaseClasses/ValveSelfActing.mo, Buildings/Experimental/DHC/Loads/Steam/BuildingTimeSeriesAtETS.mo, Buildings/Experimental/DHC/Networks/Steam/ConnectionCondensatePipe.mo, Buildings/Experimental/DHC/Networks/Steam/DistributionCondensatePipe.mo, Buildings/Experimental/DHC/Plants/Steam/BaseClasses/BoilerPolynomial.mo, Buildings/Experimental/DHC/Plants/Steam/BaseClasses/ControlVolumeEvaporation.mo, Buildings/Experimental/DHC/Plants/Steam/SingleBoiler.mo
These documentation-only changes are for Issue #3512. The only changes are to `Experimental.DHC`, since `Media.Steam` changes will occur separately through the IBPSA library ([modelica-ibpsa Issue #1793](https://github.com/ibpsa/modelica-ibpsa/issues/1793)).
Please let me know if you need any revisions or have any questions.
=> Issue3512 improve docu steam

Buildings/Experimental/DHC/Examples/Steam/SingleBoiler.mo, Buildings/Experimental/DHC/Loads/Steam/BaseClasses/ControlVolumeCondensation.mo, Buildings/Experimental/DHC/Loads/Steam/BaseClasses/SteamTrap.mo, Buildings/Experimental/DHC/Loads/Steam/BaseClasses/ValveSelfActing.mo, Buildings/Experimental/DHC/Loads/Steam/BuildingTimeSeriesAtETS.mo, Buildings/Experimental/DHC/Networks/Steam/ConnectionCondensatePipe.mo, Buildings/Experimental/DHC/Networks/Steam/DistributionCondensatePipe.mo, Buildings/Experimental/DHC/Plants/Steam/BaseClasses/BoilerPolynomial.mo, Buildings/Experimental/DHC/Plants/Steam/BaseClasses/ControlVolumeEvaporation.mo, Buildings/Experimental/DHC/Plants/Steam/SingleBoiler.mo
This merges https://github.com/lbl-srg/modelica-buildings/pull/3523 to the maintenance branch.
=> Maint 10.0.x issue3512 improve docu steam

Buildings/Templates/AirHandlersFans/Components/Interfaces/PartialHeatRecovery.mo, Buildings/Templates/AirHandlersFans/Components/Interfaces/PartialOutdoorReliefReturnSection.mo, Buildings/Templates/AirHandlersFans/Components/Interfaces/PartialOutdoorSection.mo, Buildings/Templates/AirHandlersFans/Components/Interfaces/PartialReliefReturnSection.mo, Buildings/Templates/AirHandlersFans/Interfaces/PartialAirHandler.mo, Buildings/Templates/AirHandlersFans/VAVMultiZone.mo, Buildings/Templates/AirHandlersFans/package.mo, Buildings/Templates/Components/Coils/WaterBasedCooling.mo, Buildings/Templates/Components/Coils/WaterBasedHeating.mo, Buildings/Templates/Components/Interfaces/PartialCoil.mo, Buildings/Templates/Components/Interfaces/PartialDamper.mo, Buildings/Templates/Components/Interfaces/PartialFan.mo, Buildings/Templates/Components/Interfaces/PartialSensor.mo, Buildings/Templates/Components/Interfaces/PartialValve.mo, Buildings/Templates/Components/Valves/ThreeWayModulating.mo, Buildings/Templates/Components/Valves/ThreeWayTwoPosition.mo, Buildings/Templates/Components/Valves/TwoWayModulating.mo, Buildings/Templates/Components/Valves/TwoWayTwoPosition.mo, Buildings/Templates/ZoneEquipment/Interfaces/PartialAirTerminal.mo, Buildings/Templates/ZoneEquipment/VAVBoxCoolingOnly.mo, Buildings/Templates/ZoneEquipment/VAVBoxReheat.mo, Buildings/Templates/ZoneEquipment/package.mo
This closes #3514 and is needed for https://github.com/lbl-srg/ctrl-flow-dev/issues/357.
=> Issue3514 ctrl flow annotations

Buildings/Experimental/DHC/Plants/Combined/AllElectricCWStorage.mo
This adds a missing `displayUnit` attribute.
=> Add missing displayUnit to AllElectricCWStorage.mo

Buildings/Occupants/BaseClasses/binaryVariableGeneration.mo, Buildings/Occupants/BaseClasses/exponentialVariableGeneration.mo, Buildings/Occupants/BaseClasses/linear1D.mo, Buildings/Occupants/BaseClasses/logit1D.mo, Buildings/Occupants/BaseClasses/logit1DQuadratic.mo, Buildings/Occupants/BaseClasses/logit2D.mo, Buildings/Occupants/BaseClasses/weibull1DOFF.mo, Buildings/Occupants/BaseClasses/weibull1DON.mo, Buildings/Occupants/BaseClasses/weibullVariableGeneration.mo, Buildings/package.mo
=> Added missing seed, added icon

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
Integrates https://github.com/lbl-srg/modelica-buildings/pull/3560
=> Updated urllib3

Buildings/Controls/OBC/ASHRAE/G36/Generic/TimeSuppression.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/CoolingOnly/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/DualDuctColdDuctMin/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/DualDuctMixConDischargeSensor/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/DualDuctMixConInletSensor/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/DualDuctSnapActing/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/ParallelFanCVF/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/ParallelFanVVF/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/Reheat/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/SeriesFanCVF/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/SeriesFanVVF/Controller.mo
This adds missing units to `chaRat`.
=> Added missing units

Buildings/Templates/AirHandlersFans/Components/Interfaces/PartialOutdoorReliefReturnSection.mo
=> Add annotation to fix disregarded final keyword 

Buildings/Fluid/HeatExchangers/EvaporatorCondenser.mo
This applies changes made for ibpsa/modelica-ibpsa#1810 to Buildings `maint_9.1.x`.
=> added negative sign in documentation

Buildings/Fluid/HeatExchangers/EvaporatorCondenser.mo
This PR applies the changes made in ibpsa/modelica-ibpsa#1810 to Buildings master.
=> IBPSA1810 missing negative sign in documentation

Buildings/ThermalZones/EnergyPlus_9_6_0/UsersGuide.mo
Added citation for Spawn paper.
=> Added citation to Spawn paper (maint 10.0.x)

Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/InternalResistancesOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/InternalResistancesOneUTubeNegative.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/InternalResistancesTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/InternalResistancesTwoUTubeNegative.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/partialInternalResistances.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalHEXOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalHEXTwoUTube.mo, Buildings/package.mo
This integrates IBPSA, issue 1814. The use of this function is not allowed inside other functions, and causes OpenModelica to fail during translation
=> Corrected wrong use of getInstanceName

Buildings/Resources/C-Sources/getTimeSpan.c
This implements changes from IBPSA, issue 1816
=> Added missing header file declaration (maint 9.1.x)

Buildings/Resources/C-Sources/getTimeSpan.c
This implements changes from IBPSA, issue 1816
=> Added missing header file declaration (maint 10.0.x)

Buildings/Resources/C-Sources/fileWriterFree.c, Buildings/Resources/C-Sources/fileWriterStructure.c, Buildings/Resources/C-Sources/jsonWriterInit.c
=> Added header files and ifdef statements (maint 10.0.x)

Buildings/Resources/C-Sources/fileWriterFree.c, Buildings/Resources/C-Sources/fileWriterStructure.c, Buildings/Resources/C-Sources/jsonWriterInit.c
=> Added header files and ifdef statements (maint 9.1.x)

Buildings/Resources/C-Sources/fileWriterFree.c, Buildings/Resources/C-Sources/fileWriterStructure.c, Buildings/Resources/C-Sources/jsonWriterInit.c
=> Added header files and ifdef statements

Buildings/Fluid/HeatExchangers/AirToAirHeatRecovery/BaseClasses/Effectiveness.mo, Buildings/Fluid/HeatExchangers/AirToAirHeatRecovery/WheelWithVariableSpeed.mo
@JayHuLBL please review the changes based on your comments
=> issue3538_Air2Air_recovery

Buildings/Controls/OBC/Utilities/PIDWithAutotuning/FirstOrderAMIGO.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/BaseClasses/Gain.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/BaseClasses/Validation/Gain.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/ControlProcessModel.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/Validation/ControlProcessModel.mo
This is to update the model documentation of <code>Buildings.Controls.OBC.Utilities.PIDWithAutotuning.SystemIdentification.FirstOrderTimedelayed.BaseClasses.Gain</code> to reflect the recent model change.
=> issue2884_PID_autotuning

.travis.yml
This updates the OpenModelica image.
To do:
=> Update OMC version to 1.22.1

Buildings/ThermalZones/ISO13790/Zone5R1C/ZoneHVAC.mo
This constrains choices for the media model
=> Merged IBPSA iso model (maint 10.0.x)

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Updated OMC version to 1.22.1-1 (maint 10.0.x)

.travis.yml
This updates the Optimica license file.
=> Update optimica license file (maint 10.0.x)

.travis.yml
This updates the Optimica license file
=> Update Optimica license file (maint 9.1.x)

.travis.yml
=> Update Optimica license file

Buildings/Fluid/SolarCollectors/ASHRAE93.mo, Buildings/Fluid/SolarCollectors/BaseClasses/ASHRAEHeatLoss.mo, Buildings/Fluid/SolarCollectors/BaseClasses/ASHRAESolarGain.mo, Buildings/Fluid/SolarCollectors/BaseClasses/EN12975HeatLoss.mo, Buildings/Fluid/SolarCollectors/BaseClasses/EN12975SolarGain.mo, Buildings/Fluid/SolarCollectors/BaseClasses/Examples/ASHRAEHeatLoss.mo, Buildings/Fluid/SolarCollectors/BaseClasses/Examples/ASHRAESolarGain.mo, Buildings/Fluid/SolarCollectors/BaseClasses/Examples/EN12975HeatLoss.mo, Buildings/Fluid/SolarCollectors/BaseClasses/Examples/EN12975SolarGain.mo, Buildings/Fluid/SolarCollectors/BaseClasses/IAM.mo, Buildings/Fluid/SolarCollectors/BaseClasses/PartialHeatLoss.mo, Buildings/Fluid/SolarCollectors/BaseClasses/PartialParameters.mo, Buildings/Fluid/SolarCollectors/BaseClasses/PartialSolarCollector.mo, Buildings/Fluid/SolarCollectors/Controls/BaseClasses/GCritCalc.mo, Buildings/Fluid/SolarCollectors/Controls/CollectorPump.mo, Buildings/Fluid/SolarCollectors/Data/BaseClasses/Generic.mo, Buildings/Fluid/SolarCollectors/Data/GenericASHRAE93.mo, Buildings/Fluid/SolarCollectors/Data/GenericEN12975.mo, Buildings/Fluid/SolarCollectors/EN12975.mo, Buildings/Fluid/SolarCollectors/Examples/FlatPlate.mo, Buildings/Fluid/SolarCollectors/Examples/FlatPlateShaCoeTrue.mo, Buildings/Fluid/SolarCollectors/Examples/FlatPlateTotalArea.mo, Buildings/Fluid/SolarCollectors/Examples/FlatPlateWithTank.mo, Buildings/Fluid/SolarCollectors/Examples/Tubular.mo, Buildings/Fluid/SolarCollectors/Validation/EN12975_Series.mo
This adds the changes of @jelgerjansen
=> Issue3604 solar collectors test

Buildings/Airflow/Multizone/MediumColumn.mo, Buildings/Airflow/Multizone/MediumColumnDynamic.mo, Buildings/package.mo
This corrects wrong annotations.
=> Corrected wrong annotation in MediumColumnDynamic and MediumColumnDynamic

Buildings/Airflow/Multizone/MediumColumnDynamic.mo
This corrects a wrong annotation.
=> Corrected wrong annotation in MediumColumnDynamic (10.0.x)

Buildings/Airflow/Multizone/MediumColumnDynamic.mo
This corrects a wrong annotation.
=> Corrected wrong annotation in MediumColumnDynamic

Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/SkyClearness.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/SetPoints/ReliefFan.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/SetPoints/ReliefFanGroup.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/SingleZone/VAV/SetPoints/ReliefFan.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/SingleZone/VAV/SetPoints/ReliefFanGroup.mo, Buildings/Examples/DualFanDualDuct/ClosedLoop.mo, Buildings/Examples/ScalableBenchmarks/BuildingVAV/Examples/OneFloor_OneZone.mo, Buildings/Examples/VAVReheat/BaseClasses/ASHRAE2006.mo, Buildings/package.mo
This corrects a wrong displayUnit attribute
=> Corrected displayUnit in SkyClearness and G36 (maint_9.1.x)

Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/SkyClearness.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/SetPoints/ReliefFan.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/SetPoints/ReliefFanGroup.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/SingleZone/VAV/SetPoints/ReliefFan.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/SingleZone/VAV/SetPoints/ReliefFanGroup.mo, Buildings/Examples/DualFanDualDuct/ClosedLoop.mo, Buildings/Examples/ScalableBenchmarks/BuildingVAV/Examples/OneFloor_OneZone.mo, Buildings/Examples/VAVReheat/BaseClasses/ASHRAE2006.mo, Buildings/Experimental/DHC/Plants/Cooling/BaseClasses/TankBranch.mo, Buildings/package.mo
This corrects a wrong displayUnit attribute
=> Corrected displayUnit in SkyClearness (maint_10.0.x)

Buildings/Experimental/DHC/Networks/Controls/AgentPump1Pipe.mo, Buildings/Experimental/DHC/Networks/Examples/Distribution1PipeExample.mo, Buildings/Experimental/DHC/Networks/Examples/Distribution2PipeExample.mo
This removes trailing white spaces in the Experimental package
=> Remove trailing white spaces

Buildings/Examples/Tutorial/CDL/System5.mo, Buildings/Examples/Tutorial/SpaceCooling/System3.mo
=> Removed in the documentation the reference of OnOffController

Buildings/Experimental/DHC/EnergyTransferStations/BaseClasses/PartialDirect.mo, Buildings/Experimental/DHC/EnergyTransferStations/BaseClasses/PartialIndirect.mo, Buildings/Experimental/DHC/Loads/Steam/BuildingTimeSeriesAtETS.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/Examples/SingleFamilyHouse/HeatPumpRadiantHeatingGroundHeatTransfer.mo, Buildings/package.mo
=> Corrected wrong displayUnit string

Buildings/Airflow/Multizone/MediumColumn.mo, Buildings/Airflow/Multizone/MediumColumnDynamic.mo, Buildings/Controls/OBC/CDL/Types/ZeroTime.mo, Buildings/Controls/SetPoints/SupplyReturnTemperatureReset.mo, Buildings/Fluid/Sources/BaseClasses/Outside.mo, Buildings/Fluid/Sources/BaseClasses/PartialSource_Xi_C.mo, Buildings/Fluid/Sources/Boundary_pT.mo, Buildings/Fluid/Sources/Boundary_ph.mo, Buildings/Fluid/Sources/MassFlowSource_T.mo, Buildings/Fluid/Sources/MassFlowSource_WeatherData.mo, Buildings/Fluid/Sources/MassFlowSource_h.mo, Buildings/Fluid/Sources/TraceSubstancesFlowSource.mo, Buildings/Utilities/Psychrometrics/BaseClasses/HumidityRatioVaporPressure.mo, Buildings/Utilities/Time/CalendarTime.mo, Buildings/Utilities/Time/Types/ZeroTime.mo
This corrects `HideResult` annotation, `displayUnit` annotation and extends the range of `CalendarTime`.
=> Merged IBPSA, issues 1842, 1847, 1850

Buildings/Controls/OBC/CDL/Constants.mo, Buildings/Controls/OBC/CDL/Continuous/Limiter.mo, Buildings/Controls/OBC/CDL/Continuous/MatrixGain.mo, Buildings/Controls/OBC/CDL/Continuous/Sqrt.mo, Buildings/Controls/OBC/CDL/Conversions/RealToInteger.mo, Buildings/Controls/OBC/CDL/Routing/RealVectorReplicator.mo
=> Editorial changes to CDL, and updated Constants.small (maint 9.1.x)

Buildings/Controls/OBC/CDL/Constants.mo, Buildings/Controls/OBC/CDL/Conversions/RealToInteger.mo, Buildings/Controls/OBC/CDL/Integers/Stage.mo, Buildings/Controls/OBC/CDL/Reals/Limiter.mo, Buildings/Controls/OBC/CDL/Reals/MatrixGain.mo, Buildings/Controls/OBC/CDL/Reals/Ramp.mo, Buildings/Controls/OBC/CDL/Reals/Sqrt.mo, Buildings/Controls/OBC/CDL/Routing/RealVectorReplicator.mo
=> Editorial changes to CDL, and updated Constants.small (maint 10.0.x)

Buildings/Fluid/FMI/Adaptors/Inlet.mo, Buildings/Fluid/FMI/Adaptors/Outlet.mo, Buildings/Fluid/FMI/FlowSplitter_u.mo, Buildings/Fluid/FMI/Sink_T.mo, Buildings/Fluid/FMI/Source_T.mo, Buildings/Resources/ReferenceResults/Dymola/Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_FlowSplitter_u.txt, Buildings/package.mo
=> Added missing causality (9.1.x)

Buildings/Fluid/FMI/Adaptors/Inlet.mo, Buildings/Fluid/FMI/Adaptors/Outlet.mo, Buildings/Fluid/FMI/FlowSplitter_u.mo, Buildings/Fluid/FMI/Sink_T.mo, Buildings/Fluid/FMI/Source_T.mo, Buildings/Resources/ReferenceResults/Dymola/Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_FlowSplitter_u.txt
=> Added missing causality

Buildings/Fluid/FMI/Adaptors/Inlet.mo, Buildings/Fluid/FMI/Adaptors/Outlet.mo, Buildings/Fluid/FMI/FlowSplitter_u.mo, Buildings/Fluid/FMI/Sink_T.mo, Buildings/Fluid/FMI/Source_T.mo, Buildings/Resources/ReferenceResults/Dymola/Buildings_Fluid_FMI_ExportContainers_Examples_FMUs_FlowSplitter_u.txt
=> Added missing causality (10.0.x)

Buildings/Fluid/Geothermal/Aquifer/Data/Template.mo, Buildings/Fluid/Geothermal/Aquifer/Examples/CoolingOffice.mo
This merges IBPSA, issue1855_aquifer_documentation
=> Corrected broken links in Aquifer package (maint 10.0.x)

Buildings/Fluid/Geothermal/Aquifer/Data/Template.mo, Buildings/Fluid/Geothermal/Aquifer/Examples/CoolingOffice.mo
This merges IBPSA, issue1855_aquifer_documentation
=> Corrected broken links in Aquifer package

Buildings/Airflow/Multizone/Examples/CO2TransportStep.mo, Buildings/Fluid/Sensors/Conversions/Examples/To_VolumeFraction.mo, Buildings/Fluid/Sources/Examples/TraceSubstancesFlowSource.mo, Buildings/ThermalZones/Detailed/Examples/MixedAirCO2.mo, Buildings/ThermalZones/Detailed/Validation/BESTEST/Cases9xx/Case960.mo, Buildings/ThermalZones/ReducedOrder/Validation/RoomWithLatentGain.mo, Buildings/ThermalZones/ReducedOrder/Validation/RoomWithoutLatentGain.mo
=> Update sensor parameter to avoid warning

Buildings/Experimental/DHC/Examples/Combined/BaseClasses/PartialSeries.mo, Buildings/Experimental/DHC/Loads/Combined/BaseClasses/PartialBuildingWithETS.mo, Buildings/Experimental/DHC/Loads/Combined/BuildingTimeSeriesWithETS.mo, Buildings/package.mo
This is for #3697 and partner of https://github.com/lbl-srg/modelica-buildings/pull/3708.
This closes #3697
=> Maint 10.0.x issue3697 translation fail om

Buildings/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowAIT.mo, Buildings/Resources/C-Sources/WeeklySchedule.c, Buildings/Resources/C-Sources/WeeklySchedule.h, Buildings/Utilities/IO/Files/WeeklySchedule.mo, Buildings/package.mo
This corrects a memory leak in the weekly schedule, and updates the Interval specification for the plug flow example.
=> Corrected memory leak and update plug flow example (maint 10.0.x)

Buildings/DHC/ETS/Combined/Subsystems/Borefield.mo, Buildings/DHC/Examples/Combined/BaseClasses/Borefield.mo, Buildings/DHC/Examples/Combined/BaseClasses/PartialSeries.mo, Buildings/DHC/Examples/Combined/BaseClasses/package.order, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_10_to_11.0.0.mos, Buildings/package.mo
Update conversion script and rename models.
=> Issue3727 move dhc 2 conversion script

Buildings/Controls/OBC/ASHRAE/G36/FanCoilUnit/Controller.mo
@JayHuLBL I am submitting this to update the documentation on the main FCU controller. Please merge this before merging #3627. Thanks!
=> Updated documentation for main controller with plant request information

.github/workflows/formatting.yml, .travis.yml
This is the version scheduled for release 5.1.0
=> Changed version of BuildingsPy

.github/workflows/formatting.yml, .travis.yml, Buildings/package.mo
This updates the release notes and also updates BuildingsPy to 5.1.0
=> Prepared for 10.1.1 maintenance

.github/workflows/formatting.yml, .travis.yml, Buildings/package.mo
Updated release notes and updated BuildingsPy to 5.1.0.
=> Patch release notes 11 0 1

.github/workflows/formatting.yml, .travis.yml, Buildings/package.mo
This updates the release notes and also updates BuildingsPy to 5.1.0
=> Prepared for 9.1.3 maintenance

Buildings/ThermalZones/Detailed/UsersGuide.mo, Buildings/Utilities/Plotters/Examples/SingleZoneVAVSupply_u.mo
This corrects broken hyperlinks in the documentation.
=> Corrected broken hyperlinks (maint 10.0.x)

Buildings/DHC/Loads/Steam/BuildingTimeSeriesAtETS.mo, Buildings/Resources/C-Sources/WeeklySchedule.c, Buildings/Resources/C-Sources/WeeklySchedule.h, Buildings/Resources/Data/schedule.txt, Buildings/Resources/Data/scheduleWindows.txt, Buildings/ThermalZones/ISO13790/Validation/BESTEST/Case900.mo, Buildings/ThermalZones/ISO13790/Validation/BESTEST/Data/Case600Results.mo, Buildings/ThermalZones/ISO13790/Zone5R1C/Zone.mo, Buildings/Utilities/IO/Files/Examples/WeeklySchedule.mo
This updates the schedule objects and also removes connections to itself.
=> Ibpsa sync issue1874 connectors floating points

Buildings/UsersGuide/ReleaseNotes/Version_11_1_0.mo, Buildings/UsersGuide/ReleaseNotes/package.mo, Buildings/UsersGuide/ReleaseNotes/package.order, Buildings/package.mo
This updates the version number to 11.1.0 due to the new heat pump model.
=> Updated version to 11.1.0

Buildings/DHC/Examples/Combined/BaseClasses/Borefield.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Examples/InternalHEXTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalHEXOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalHEXTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalResistancesOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalResistancesTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/PartialBorehole.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/PartialInternalHEX.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/PartialInternalResistances.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/Examples/BoreholeDynamics.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/OneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/TwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/PartialBorefield.mo, Buildings/Fluid/Geothermal/Borefields/Examples/Borefields.mo, Buildings/Fluid/Geothermal/Borefields/Examples/RectangularBorefield.mo, Buildings/Fluid/Geothermal/Borefields/UsersGuide.mo, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_11_to_12.0.0.mos, Buildings/UsersGuide/ReleaseNotes/Version_12_0_0.mo
This integrates https://github.com/ibpsa/modelica-ibpsa/issues/1885
=> Removed parameter dynFil in borefield models

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
See https://github.com/lbl-srg/modelica-buildings/pull/3840
=> Increased version of python requests

Buildings/DHC/Loads/HotWater/DirectHeatExchangerWithElectricHeat.mo, Buildings/DHC/Loads/HotWater/StorageTankWithExternalHeatExchanger.mo
=> Corrected malformed url

Buildings/Fluid/HeatPumps/ModularReversible/Examples/LargeScaleWaterToWater_OneRoomRadiator.mo, Buildings/Fluid/SolarCollectors/Examples/FlatPlateWithTank.mo
This merges the IBPSA master branch.
=> Merge IBPSA master

Buildings/Controls/OBC/Utilities/Validation/OptimalStartCoolingNegativeStartTime.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartCoolingPositiveStartTime.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartHeating.mo, Buildings/Resources/Scripts/Dymola/Controls/OBC/Utilities/Validation/OptimalStartCoolingNegativeStartTime.mos, Buildings/Resources/Scripts/Dymola/Controls/OBC/Utilities/Validation/OptimalStartCoolingPositiveStartTime.mos, Buildings/Resources/Scripts/Dymola/Controls/OBC/Utilities/Validation/OptimalStartHeating.mos
This PR is to apply the same changes in #3867 to maint_10.0.x.
=> issue 3865 change OptimalStart test tolerance maint 10

Buildings/Experimental/DHC/Loads/Steam/BuildingTimeSeriesAtETS.mo
This corrects a wrong graphical annotation.
=> Corrected wrong annotation (main 10.0.x)

Buildings/Examples/Tutorial/SimpleHouse/SimpleHouse3.mo, Buildings/Resources/C-Sources/WeeklySchedule.c, Buildings/Resources/C-Sources/WeeklyScheduleFree.c, Buildings/Resources/C-Sources/WeeklyScheduleGetValue.c, Buildings/UsersGuide/ReleaseNotes/Version_11_1_0.mo, Buildings/Utilities/IO/Files/BaseClasses/WeeklyScheduleObject.mo, Buildings/Utilities/IO/Files/WeeklySchedule.mo
This corrects the WeeklyScheduleObject to comply with the Modelica Language Specification
=> Merged changes from Modelica master (maint 11.x)

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
=> Updated urllib3 (maint 10.0.x)

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
=> Updated urllib3 (maint 11.x)

Buildings/Resources/C-Sources/WeeklySchedule.c, Buildings/Resources/C-Sources/WeeklySchedule.h, Buildings/Resources/C-Sources/WeeklyScheduleFree.c, Buildings/Resources/C-Sources/WeeklyScheduleGetValue.c, Buildings/Utilities/IO/Files/BaseClasses/WeeklyScheduleObject.mo, Buildings/Utilities/IO/Files/WeeklySchedule.mo, Buildings/package.mo
This corrects the WeeklyScheduleObject to comply with the Modelica Language Specification
=> Merged changes from Modelica master (maint 10.0.x)

Buildings/DHC/Plants/BaseClasses/PartialPlant.mo, Buildings/DHC/Plants/Combined/Subsystems/CoolingTowerGroup.mo
=> Corrected annotation for AllElectricCWStorage

Buildings/DHC/Plants/BaseClasses/PartialPlant.mo, Buildings/DHC/Plants/Combined/Subsystems/CoolingTowerGroup.mo
=> Corrected annotation (maint 11.x)

Buildings/Experimental/DHC/Plants/BaseClasses/PartialPlant.mo, Buildings/Experimental/DHC/Plants/Combined/Subsystems/CoolingTowerGroup.mo
=> Corrected annotation (maint 10.0.x)

Buildings/Air/Systems/SingleZone/VAV/BaseClasses/ControllerEconomizer.mo, Buildings/Controls/OBC/ASHRAE/G36/Generic/TimeSuppression.mo, Buildings/Obsolete/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Reheat/SystemRequests.mo, Buildings/UsersGuide/ReleaseNotes/Version_12_0_0.mo
This is for #3915.
This should be the last PR needed to resolve the blocking points in #3863.
=> Fix algebraic loops appearing after refactoring hold block

Buildings/Fluid/Delays/DelayFirstOrder.mo
=> Moved parameter tau for DelayFirstOrder to main tab

Buildings/Fluid/Delays/DelayFirstOrder.mo
This merges changes from IBPSA.
=> Moved parameter to tau for DelayFirstOrder to main tab (maint_10.0.x)

Buildings/Fluid/Delays/DelayFirstOrder.mo
This merges changes from IBPSA.
=> Moved parameter to tau for DelayFirstOrder to main tab (maint 11.x)

Buildings/Fluid/CHPs/BaseClasses/EfficiencyCurve.mo
=> removed double icon

Buildings/BoundaryConditions/GroundTemperature/BaseClasses/surfaceTemperature.mo, Buildings/Electrical/Transmission/BaseClasses/BaseCable.mo, Buildings/HeatTransfer/Conduction/BaseClasses/der_temperature_u.mo, Buildings/UsersGuide/ReleaseNotes/Version_12_0_0.mo, Buildings/Utilities/Math/Functions/round.mo
=> Corrected compliance with MSL (master)

Buildings/Resources/C-Sources/cfdSendStopCommand.c
This ports https://github.com/lbl-srg/modelica-buildings/pull/3995
=> Added NULL pointer (maint 10)

Buildings/Resources/C-Sources/cfdSendStopCommand.c
This ports https://github.com/lbl-srg/modelica-buildings/pull/3995
=> Added NULL pointer (maint 9.1)

Buildings/Resources/C-Sources/cfdSendStopCommand.c
This ports https://github.com/lbl-srg/modelica-buildings/pull/3995
=> Added NULL pointer (maint 11)

Buildings/Fluid/CHPs/OrganicRankine/Data/Generic.mo, Buildings/Fluid/Geothermal/ZonedBorefields/BaseClasses/HeatTransfer/shiftAggregationCells.mo, Buildings/Fluid/Geothermal/ZonedBorefields/BaseClasses/HeatTransfer/temporalSuperposition.mo, Buildings/Fluid/Geothermal/ZonedBorefields/Data/Borefield/Validation.mo, Buildings/Fluid/Geothermal/ZonedBorefields/Data/Configuration/Template.mo
=> issue3992 broken html links

Buildings/Applications/DataCenters/ChillerCooled/Equipment/BaseClasses/SignalFilter.mo
=> Correct dimension in actuator model in data center package

Buildings/Controls/OBC/CDL/Reals/LimitSlewRate.mo
This has changes to the documentation only
=> Revised documentation of SlewRateLimiter

Buildings/Airflow/Multizone/BaseClasses/DoorDiscretized.mo, Buildings/Resources/Scripts/BuildingsPy/conf.yml
This changes a protected parameter to an input, which is assinged by the extending class
=> Merges IBPSA, issues1935_unprotectdhDiscretizedDoor

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml, bin/runUnitTests.py
=> Update OpenModelica to 1.24.0

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml, bin/runUnitTests.py
This updates the OpenModelica image to 1.24.0
=> Update OpenModelica (maint 11)

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml, bin/runUnitTests.py
This updates OpenModelica to 1.24.0
=> Update OpenModelica to 1.24 (maint 10)

.travis.yml, Buildings/BoundaryConditions/GroundTemperature/BaseClasses/surfaceTemperature.mo, Buildings/Electrical/Transmission/BaseClasses/BaseCable.mo, Buildings/HeatTransfer/Conduction/BaseClasses/der_temperature_u.mo, Buildings/Resources/Scripts/BuildingsPy/conf.yml, Buildings/Utilities/Math/Functions/round.mo
=> Correct compliance with MSL (maint 9.1)

Buildings/Electrical/DC/Loads/Resistor.mo
=> Changed guard against division by zero

Buildings/Airflow/Multizone/BaseClasses/DoorDiscretized.mo, Buildings/Electrical/DC/Loads/Resistor.mo, Buildings/Electrical/Interfaces/Load.mo, Buildings/Resources/Scripts/BuildingsPy/conf.yml
This closes #4048. It also merges minor changes from IBPSA.
=> Change initialization of electrical load

Buildings/Electrical/DC/Loads/Resistor.mo, Buildings/Electrical/Interfaces/Load.mo, Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Change initialization of electrical load (maint 10)

Buildings/Electrical/DC/Loads/Resistor.mo, Buildings/Electrical/Interfaces/Load.mo, Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Change initialization of electrical load (maint 11)

Buildings/ThermalZones/EnergyPlus_24_2_0/UsersGuide.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/UsersGuide.mo, README.md
=> Updated Spawn installation instructions

Buildings/DHC/ETS/Combined/Examples/ChillerOnly.mo, Buildings/DHC/ETS/Combined/Validation/ChillerOnly.mo, Buildings/DHC/ETS/Combined/Validation/ChillerWSE.mo
This removes a duplicate signal connection
=> Removed duplicate connection in ETS model (maint 11.x)

Buildings/DHC/Networks/Controls/AgentPump1Pipe.mo
This adds the DOI. The old link is no longer valid.
=> Added doi to AgentPump1Pipe.mo

Buildings/Controls/OBC/CDL/Logical/TrueFalseHold.mo
This is for #4082, and a follow-up to https://github.com/lbl-srg/modelica-buildings/pull/3967#issuecomment-2311927171
=> Merge elsewhen clauses

Buildings/Fluid/MixingVolumes/Validation/MixingVolume.mo
This merges IBPSA, https://github.com/ibpsa/modelica-ibpsa/issues/1952
This addresses https://github.com/OpenModelica/OpenModelica/issues/13198
=> Changed tolerance of assertion blocks

Buildings/Fluid/FixedResistances/BuriedPipes/BaseClasses/groundCouplingFactors.mo
=> corrected the path

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Updated OCT image to 1.55.11 (maint 11.x)

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml
=> Updated OCT image to 1.55.11

.github/workflows/formatting.yml
This updates the runner to a more recent version of Ubuntu
=> Updated runner to Ubuntu 24.04

Buildings/Fluid/HeatPumps/ModularReversible/BaseClasses/PartialReversibleRefrigerantMachine.mo
=> Corrected conditions to disable output connectors

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
This applies a security patch for Jinja
=> Updated Jinja to 3.1.6

Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/BrighteningCoefficient.mo, Buildings/Controls/SetPoints/OccupancySchedule.mo, Buildings/Electrical/PhaseSystems/ThreePhase_d.mo, Buildings/Electrical/PhaseSystems/package.mo, Buildings/Fluid/Actuators/Dampers/MixingBox.mo, Buildings/Fluid/BaseClasses/ActuatorFilter.mo, Buildings/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo, Buildings/Fluid/HeatExchangers/BaseClasses/epsilon_ntuZ.mo, Buildings/Fluid/HeatExchangers/BaseClasses/ntu_epsilonZ.mo, Buildings/Fluid/HeatExchangers/WetCoilEffectivenessNTU.mo, Buildings/Fluid/HeatPumps/ModularReversible/Examples/AirToWater2D_OneRoomRadiator.mo, Buildings/Fluid/HeatPumps/ModularReversible/Examples/BaseClasses/PartialOneRoomRadiator.mo, Buildings/Fluid/HeatPumps/ModularReversible/Examples/CarnotWithLosses_OneRoomRadiator.mo, Buildings/Fluid/HeatPumps/ModularReversible/Examples/LargeScaleWaterToWater_OneRoomRadiator.mo, Buildings/Fluid/HeatPumps/ModularReversible/Examples/Modular_OneRoomRadiator.mo, Buildings/Fluid/Movers/BaseClasses/FlowMachineInterface.mo, Buildings/Fluid/SolarCollectors/Validation/EN12975_Array.mo, Buildings/Fluid/Storage/BaseClasses/PartialStratified.mo, Buildings/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case600.mo, Buildings/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case600FF.mo, Buildings/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo
This corrects replacing non-replaceable medium bindings, and removes import statements
=> Merged IBPSA, issue 1981

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
=> Updated Jinja to 3.1.6 (maint 11.x)

.travis.yml, Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
=> Updated Jinja to 3.1.6 (maint 10.x)

Buildings/Resources/Scripts/BuildingsPy/conf.yml
This increases the timeout for jenkins
=> Master branch, increase timeout

Buildings/Resources/Scripts/BuildingsPy/conf.yml
This increases the timeout for jenkins
=> Maint 11.x, increase timeout

Buildings/Fluid/HeatPumps/ModularReversible/Data/TableData2D/EN14511/WAMAK_WaterToWater_220kW.mo
This PR is to port changes made in ibpsa/modelica-ibpsa#1989.
This PR only changes documentation texts and will not influence any test results.
=> ibpsa 1989 fix WAMAK link

.github/workflows/formatting.yml, .travis.yml, Buildings/UsersGuide/ReleaseNotes/Version_10_1_1.mo, Buildings/UsersGuide/ReleaseNotes/Version_11_1_0.mo, Buildings/UsersGuide/ReleaseNotes/package.mo, Buildings/UsersGuide/ReleaseNotes/package.order, Buildings/package.mo, README.md
=> Maint 11.x - update files for release

Buildings/Resources/Documentation/userGuide/build/html/_sources/gettingStarted.rst.txt, Buildings/Resources/Documentation/userGuide/build/html/gettingStarted.html, Buildings/Resources/Documentation/userGuide/source/gettingStarted.rst, Buildings/package.mo, README.md
=> Maint 10.0.x - update files for release

Buildings/UsersGuide/ReleaseNotes/Version_11_1_0.mo, Buildings/UsersGuide/ReleaseNotes/Version_12_0_0.mo, Buildings/UsersGuide/ReleaseNotes/Version_12_0_1.mo, Buildings/UsersGuide/ReleaseNotes/package.mo, Buildings/UsersGuide/ReleaseNotes/package.order, Buildings/package.mo
Updated files for post 12.0.0 release.
=> Add files for developments past version 12.0.0

Buildings/Fluid/Actuators/Dampers/Validation/PressureIndependent.mo
=> Fixes OMC issue #13800

Buildings/Controls/OBC/ASHRAE/G36/Plants/Boilers/PrimaryController.mo, Buildings/Controls/OBC/ASHRAE/G36/Plants/Boilers/Types/BoilerTypes.mo, Buildings/Examples/BoilerPlants/ClosedLoopTest.mo, Buildings/Resources/Scripts/Dymola/Examples/BoilerPlants/ClosedLoopTest.mos
@AntoineGautier I reverted the boiler types definition to use the Integer constants. This fixed the translation issues being reported in the unit test. Please let me know if you have any questions. Thanks!
=> Issue2180 boiler plant nov23

Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_0.11_to_0.12.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_0.12_to_1.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.0_to_1.1.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.1_to_1.2.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.4_to_1.5.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.5_to_1.6.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.6_to_2.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_10_to_11.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_11_to_12.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_2.1_to_3.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_3.0_to_4.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_4.0_to_5.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_5_to_6.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_6_to_7.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_7_to_8.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_8_to_9.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_9_to_10.0.0.mos
=> Updated conversion script to remove clear commands

Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_0.11_to_0.12.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_0.12_to_1.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.0_to_1.1.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.1_to_1.2.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.4_to_1.5.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.5_to_1.6.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.6_to_2.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_10_to_11.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_11_to_12.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_2.1_to_3.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_3.0_to_4.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_4.0_to_5.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_5_to_6.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_6_to_7.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_7_to_8.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_8_to_9.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_9_to_10.0.0.mos
=> Updated conversion script to remove clear commands (maint 12.x)

Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_0.11_to_0.12.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_0.12_to_1.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.0_to_1.1.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.1_to_1.2.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.4_to_1.5.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.5_to_1.6.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.6_to_2.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_10_to_11.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_2.1_to_3.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_3.0_to_4.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_4.0_to_5.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_5_to_6.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_6_to_7.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_7_to_8.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_8_to_9.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_9_to_10.0.0.mos
=> Updated conversion script to remove clear commands (maint 11.x)

Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_0.11_to_0.12.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_0.12_to_1.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.0_to_1.1.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.1_to_1.2.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.4_to_1.5.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.5_to_1.6.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_1.6_to_2.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_2.1_to_3.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_3.0_to_4.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_4.0_to_5.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_5_to_6.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_6_to_7.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_7_to_8.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_8_to_9.0.0.mos, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_9_to_10.0.0.mos
=> Updated conversion script to remove clear commands (maint 10.x)

Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/C-Sources/plotSendReal.c, Buildings/Utilities/Plotters/BaseClasses/PartialPlotter.mo
=> Corrected comparison of boolean with real. Corrected type comparison (maint 12)

Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/C-Sources/plotSendReal.c, Buildings/Utilities/Plotters/BaseClasses/PartialPlotter.mo
=> Corrected comparison of boolean with real. Corrected type comparison (maint 10)

Buildings/HeatTransfer/Conduction/BaseClasses/der_temperature_u.mo, Buildings/UsersGuide/ReleaseNotes/Version_12_0_1.mo
=> Reformulated function to avoid binding eqn warning (maint 12)

Buildings/HeatTransfer/Conduction/BaseClasses/der_temperature_u.mo, Buildings/UsersGuide/ReleaseNotes/Version_12_0_1.mo
=> Reformulated function to avoid binding equation not a parameter expression warning

Buildings/Fluid/HeatExchangers/CoolingTowers/Validation/MerkelEnergyPlus.mo, Buildings/Fluid/HeatExchangers/CoolingTowers/Validation/MerkelNominal.mo
This is for issue #4189. 
@mwetter - I have not yet been able to get the unit tests running on my new computer, so those steps are not included in this PR. I'm opening this now regardless to avoid delays. All changes are noted in the issue comment [here](https://github.com/lbl-srg/modelica-buildings/issues/4189#issuecomment-2842112575). 
Please let me know if you need anything else. Thanks for the opportunity to improve this model!
=> Issue4189 merkel ua nominal

Buildings/HeatTransfer/Conduction/BaseClasses/der_temperature_u.mo, Buildings/UsersGuide/ReleaseNotes/Version_11_1_1.mo
=> Reformulated function to avoid binding eqn warning (maint 11)

Buildings/HeatTransfer/Conduction/BaseClasses/der_temperature_u.mo, Buildings/package.mo
=> Reformulated function to avoid binding eqn warning (maint 10)

Buildings/Fluid/Geothermal/ZonedBorefields/BaseClasses/PartialStorage.mo
=> Issue 4199 Fix nominal mass flow in boreholes

Buildings/Electrical/Interfaces/PartialWindTurbine.mo
=> Guarded against rounding error for wind cutoff (maint 12)

Buildings/Electrical/Interfaces/PartialWindTurbine.mo
=> Guarded against rounding error for wind cutoff

Buildings/Utilities/Plotters/Configuration.mo
=> Corrected wrong type comparison (maint 12)

Buildings/Utilities/Plotters/Configuration.mo
=> Corrected wrong type comparison

Buildings/Fluid/AirFilters/BaseClasses/FiltrationEfficiency.mo, Buildings/Fluid/AirFilters/Data/Characteristics/FiltrationEfficiencyParameters.mo, Buildings/Fluid/AirFilters/Data/Generic.mo, Buildings/Fluid/AirFilters/Empirical.mo
This PR includes small updates to improve the model documentation, along with the addition of a reference to address https://github.com/lbl-srg/modelica-buildings/pull/3676#discussion_r1943784521.
=> Issue3618 air filter

Buildings/Utilities/Plotters/Configuration.mo
=> Corrected wrong type comparison (maint 10)

Buildings/Controls/OBC/Utilities/PIDWithAutotuning/Relay/BaseClasses/TuningMonitor.mo
This PR addresses https://github.com/lbl-srg/modelica-buildings/issues/4269
=> issue4269_AutoTunPID_verification

Buildings/Controls/OBC/Utilities/PIDWithAutotuning/Relay/BaseClasses/TuningMonitor.mo
This integrates the changes of PR #4269 to the maintenance branch
=> Increased tolerance for check against zero

.travis.yml, Buildings/Resources/Scripts/travis/Makefile, bin/verifyFiles.py
=> added prefix r

Buildings/Fluid/Geothermal/Borefields/Data/Filling/Template.mo
This is for issue 2014 of IBPSA
=> Guarded against division by zero

Buildings/Fluid/Geothermal/Borefields/Data/Filling/Template.mo, Buildings/UsersGuide/ReleaseNotes/Version_12_1_1.mo
This is for issue 2041 of IBPSA
=> Guarded against division by zero (maint 12.x)

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
This applies https://github.com/lbl-srg/modelica-buildings/pull/4328 and https://github.com/lbl-srg/modelica-buildings/pull/4327
=> Apply python security patch to maint 10.0.x

Buildings/Resources/Documentation/userGuide/requirements.txt, Buildings/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt
This applies https://github.com/lbl-srg/modelica-buildings/pull/4328 and https://github.com/lbl-srg/modelica-buildings/pull/4327
=> Apply python security patch to maint 11.x

Buildings/Resources/Documentation/userGuide/requirements.txt
For https://github.com/lbl-srg/modelica-buildings/pull/4341
=> Bump urllib

Buildings/ThermalZones/ReducedOrder/Examples/SimpleRoomFourElementsTraceSubstance.mo
=> Added missing annotation 'Interval'

Buildings/Resources/C-Sources/cfdCosimulation.h, Buildings/Resources/C-Sources/cfdSendStopCommand.c, Buildings/Resources/C-Sources/cfdStartCosimulation.c, Buildings/Resources/C-Sources/cfdcosim.c, Buildings/ThermalZones/Detailed/BaseClasses/CFDExchange.mo, Buildings/ThermalZones/Detailed/BaseClasses/CFDThread.mo
For #4379.
This also adds missing impure declarations.
=> Added missing header files in FFD files (maint_10.0.x)

Buildings/Resources/C-Sources/cfdCosimulation.h, Buildings/Resources/C-Sources/cfdSendStopCommand.c, Buildings/Resources/C-Sources/cfdStartCosimulation.c, Buildings/Resources/C-Sources/cfdcosim.c, Buildings/ThermalZones/Detailed/BaseClasses/CFDExchange.mo, Buildings/ThermalZones/Detailed/BaseClasses/CFDThread.mo
For #4379.
This also adds missing impure declarations.
=> Added missing header files in FFD files (maint_12.x)

Buildings/Resources/C-Sources/cfdCosimulation.h, Buildings/Resources/C-Sources/cfdSendStopCommand.c, Buildings/Resources/C-Sources/cfdStartCosimulation.c, Buildings/Resources/C-Sources/cfdcosim.c, Buildings/ThermalZones/Detailed/BaseClasses/CFDExchange.mo, Buildings/ThermalZones/Detailed/BaseClasses/CFDThread.mo
For #4379.
This also adds missing impure declarations.
=> Added missing header files in FFD files (maint_11.x)
