Buildings/Electrical/AC/OnePhase/Loads/Resistive.mo, Buildings/Electrical/DC/Loads/Conductor.mo, Buildings/Electrical/DC/Loads/Resistor.mo, Buildings/Electrical/Interfaces/ResistiveLoad.mo, Buildings/Electrical/Interfaces/package.order
The simple addition of a new interface for resistive models (basically an empty wrapper of the basic Load interface) seems to help the OpenModelica parser.
This is supposed to fix issue #415.
=> Tentative to fix issue #415. Adding a dummy interface for resistive models

Buildings/Fluid/Storage/BaseClasses/IndirectTankHeatExchanger.mo, Buildings/Fluid/Storage/StratifiedEnhancedInternalHex.mo, Buildings/Fluid/Storage/UsersGuide.mo, Buildings/package.mo
This adds the option to configure the dynamics of the heat exchanger metal independently of the dynamics of the fluid.
The default settings are such that the results are as before, and the model is backwards compatible.
This will close #434 .
=> Issue434 tan dyn

Buildings/Fluid/HeatExchangers/RadiantSlabs/SingleCircuitSlab.mo, Buildings/HeatTransfer/Conduction/MultiLayer.mo, Buildings/HeatTransfer/Conduction/SingleLayer.mo, Buildings/HeatTransfer/Data/OpaqueConstructions.mo
This is for #614. This addresses  an `Array index out of bounds: 3, index expression: j` compilation issue in JModelica.
This however does not cause the model to compile as JModelica reports following error:
> Error: in file 'null':
> Semantic error at line 0, column 0: Index reduction failed: Maximum number of differentiations has been reached.
The refactoring is however better as it does not expose the parameter `nSta2` anymore.
The refactoring does not change any reference results.
=> Refactor for JModelica translation.

Buildings/Resources/C-Sources/cfdCosimulation.h, Buildings/Resources/C-Sources/cfdStartCosimulation.c
@mwetter
I think I have added the compiler directive which works with MinGW. However I am now getting following error messages:
```
FMIL: module = FMICAPI, log level = 5: Calling fmiInitialize
FMIL: module = Model, log level = 4: [INFO][FMU status:OK] <JMIRuntime><value name="build_date">"Feb  1 2017"</value> <value name="build_time">"15:39:37"</value></JMIRuntime>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <ModelicaMessage category="warning"><value name="msg">"... loading ""tab1"" from ""Z:/Ubuntu/proj/buildings_library/models/modelica/git/buildings/modelica-buildings/Buildings/Resources/weatherdata/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.mos""&#10;"</value></ModelicaMessage>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <ModelicaMessage …
```
=> Add compiler directives.

Buildings/Experimental/DistrictHeatingCooling/Plants/LakeWaterHeatExchanger_T.mo, Buildings/Experimental/DistrictHeatingCooling/Plants/Validation/LakeWaterHeatExchanger_T_Heating.mo
Fixed sign of TApproach in LakeWaterHeatexchanger model, Fixed mistake in validation model (changed 275.15K to 273.15K)
=> Fixed TApproach mistake and mistake in validation model

Buildings/Fluid/Chillers/BaseClasses/Carnot.mo
Added dT in CarnotBaseclass, default is set to 0 (set as a start value as described in style guide)
=> 650_bayWaterHex: Added dT in Carnot baseclass

.travis.yml
install scipy, numpy and matplotlib v
instead of using system_site_packages
https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
=> install scipy, numpy and matplotlib via pip

.travis.yml
cache pip packages as mentioned in #663 
pip packages are shared between the builds.
Might give a small speedup here, as there are many builds in parallel.
=> cache pip packages

Buildings/Resources/Images/Controls/OBC/ASHRAE/G36/Atomic/EconDamperLimitsMultiZone.svg, Buildings/Resources/Images/Controls/OBC/ASHRAE/G36/Atomic/EconDamperLimitsSingleZone.svg, Buildings/Resources/Images/Controls/OBC/ASHRAE/G36/Atomic/EconEnableDisableStateMachine.svg, Buildings/Resources/Images/Controls/OBC/ASHRAE/G36/Atomic/EconModulationMultiZone.svg, Buildings/Resources/Images/Controls/OBC/ASHRAE/G36/Atomic/EconModulationSingleZone.svg
This PR adds all ```svg``` files used in creating ```png``` images for economizer atomic sequences, both single and multiple zone.
=> Added svg files for economizer sequences

Buildings/Controls/OBC/ASHRAE/G36/AHUs/SingleZone/Economizers/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36/AHUs/SingleZone/Economizers/Subsequences/DamperLimits.mo
Redefined affected min and max parameter limits in ```Buildings.Controls.OBC.ASHRAE.G36.AHUs.SingleZone.Economizers.Subsequences.DamperLimits``` in order to avoid cyclical dependencies.
=> Issue 885 Fix cyclically dependent constants or parameters (for Open Modelica)

Buildings/Controls/OBC/UnitConversions/From_ton.mo, Buildings/Controls/OBC/UnitConversions/To_ton.mo, Buildings/Controls/OBC/UnitConversions/Validation/From_ton.mo, Buildings/Controls/OBC/UnitConversions/Validation/To_ton.mo, Buildings/Controls/OBC/UnitConversions/Validation/package.order, Buildings/Controls/OBC/UnitConversions/package.order, Buildings/Resources/ReferenceResults/Dymola/Buildings_Controls_OBC_UnitConversions_Validation_From_ton.txt, Buildings/Resources/ReferenceResults/Dymola/Buildings_Controls_OBC_UnitConversions_Validation_To_ton.txt, Buildings/Resources/Scripts/Dymola/Controls/OBC/UnitConversions/Validation/From_ton.mos, Buildings/Resources/Scripts/Dymola/Controls/OBC/UnitConversions/Validation/To_ton.mos, Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Controls.OBC.UnitConversions.Validation.From_ton.mos, Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Controls.OBC.UnitConversions.Validation.To_ton.mos, Buildings/Resources/src/Controls/OBC/UnitConversions/unit_converters.py
OBC case study data provides chiller tonnage timeseries, thus adding a unit converter between the ton of refrigeration and watt.
Closes #1255
=> added unit conversion to and from ton of refrigeration #1255

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Economizers/Controller.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Economizers/Subsequences/Limits.mo, Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_5_to_6.0.0.mos
Closes #1275.
Renamed ```minVOutMinFansSpePos``` to ```yDam_VOutMin_minSpe``` and added to conversion script.
=> Renamed variable in single zone econ limits

Buildings/Controls/OBC/CDL/Continuous/MultiSum.mo
@mwetter:
I had just copied the input icon from another block and had not paid attention to the name, description and location change in the code. I changed back the input name and location.
I also made the output icon smaller, to be consistent with other similar blocks like yMax.
=> changed back the input name and placement

Buildings/Controls/OBC/package.order
@mwetter:
The package order has been refactored using BuildingsPy package. 
A blank line at the end was removed.
=> issue1364 OutdoorLights package order

Buildings/Resources/C-Sources/cfdExchangeData.c, Buildings/Resources/C-Sources/cfdSendStopCommand.c, Buildings/Resources/C-Sources/cfdStartCosimulation.c, Buildings/Resources/C-Sources/cfdcosim.c
1. initialize pointers in constructor to avoid a segmentation fault
2. clean format
=> initialize pointers in constructor to avoid segfault and clean format

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Economizers/Controller.mo
=> Issue1508 model to block

Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Controller.mo
=> added default component name, #1809

Buildings/Controls/OBC/CDL/Logical/Latch.mo, Buildings/Controls/OBC/CDL/Logical/Toggle.mo, Buildings/package.mo
This closes #1823 
@JayHuLBL : Please see these changes. These are needed for the models to run with OpenModelica and lead to much simpler implementation. I will merge it if all tests pass. I essentially put all assigments in the `when` section rather than a separate `if-then` section, and simplified for cases where we know what values the variables have.
=> Simplified Toggle and Latch for #1823

Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_6_to_7.0.0.mos
@AntoineGautier : This patches a misplaced bracket in the conversion script for the MixingBoxMinimumFlow.
Also, I don't think you need to list
```
{"Buildings.Fluid.Actuators.Dampers.PressureIndependent",
"Fluid.Actuators.Dampers.PressureIndependent",
"Actuators.Dampers.PressureIndependent",
"Dampers.PressureIndependent",
"PressureIndependent"}
```
because
```
{"Buildings.Fluid.Actuators.Dampers.PressureIndependent"}
```
suffices.
=> Corrected misplaced bracket.

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/SingleZone/VAV/Economizers/Subsequences/Enable.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/TerminalUnits/Validation/Controller.mo, Buildings/Controls/OBC/CDL/Continuous/MultiMax.mo, Buildings/Controls/OBC/CDL/Continuous/MultiMin.mo, Buildings/Controls/OBC/CDL/Continuous/Sources/TimeTable.mo, Buildings/Controls/OBC/OutdoorLights/DaylightControlled.mo, Buildings/Controls/OBC/Shade/Shade_H.mo, Buildings/Controls/OBC/Shade/Shade_T.mo, Buildings/Controls/OBC/Utilities/BaseClasses/OptimalStartCalculation.mo, Buildings/Controls/OBC/Utilities/OptimalStart.mo
=> added default name and fixed parameter specifications, #1944

Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusFMU.c
This patch will write a `ModelicaError` if the idf or epw file does not exist or is not readable.
=> Wrote ModelicaError if file does not exist

Buildings/Fluid/HeatExchangers/RadiantSlabs/BaseClasses/Functions/AverageResistance.mo
This pull request addresses <a href="https://github.com/lbl-srg/modelica-buildings/issues/2009">issue2009_radiantSlab</a> by updating the model AverageResistance warning   and updating the documentation
=> Pullrequest issue2009_radiantSlab warning and documentation

Buildings/Resources/C-Sources/EnergyPlus/BuildingInstantiate.h, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusFMU.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusUtil.c, Buildings/Resources/C-Sources/EnergyPlus/EnergyPlusUtil.h, Buildings/Resources/C-Sources/EnergyPlus/OutputVariableInstantiate.h, Buildings/Resources/C-Sources/EnergyPlus/ZoneInstantiate.h
C sources in Buildings/Resources/C-Sources/EnergyPlus patched to allow building FMUs on Windows, working around the unistd.h and execinfo.h includes.
The printBacktrace function will do nothing on Windows since I'm not aware of a Windows-compiler-portable backtrace approach and didn't take the time to build one.
=> issue1129_energyPlus_zone branch patched for Windows

Buildings/Resources/Documentation/userGuide/build/html/.buildinfo, Buildings/Resources/Documentation/userGuide/build/html/_sources/development.rst.txt, Buildings/Resources/Documentation/userGuide/build/html/development.html, Buildings/Resources/Documentation/userGuide/source/development.rst
This corrects the formatting which lead to a code section in the user guide not being shown.
=> Corrected formatting

Buildings/Fluid/Interfaces/StaticTwoPortConservationEquation.mo, Buildings/Fluid/MixingVolumes/BaseClasses/PartialMixingVolume.mo
This merges the IBPSA master with new settings for the start value of `hOut` for the steady state balance.
=> Merged IBPSA master

Buildings/Controls/OBC/ASHRAE/G36_PR1/AHUs/MultiZone/VAV/SetPoints/OutdoorAirFlow/Zone.mo
This avoids use of non-literal value as the min attribute if the area is computed based on the volume obtained from EnergyPlus
=> Changed min value to a default assignment

Buildings/ThermalZones/EnergyPlus/Actuator.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/FMUZoneAdapter.mo, Buildings/ThermalZones/EnergyPlus/OutputVariable.mo
This uses the same assignments for all classes that assign `startTime` for the Spawn coupling.
=> Revised implementation to consistently use the parameter startTime

Buildings/ThermalZones/EnergyPlus/Validation/ThermalZone/TwoIdenticalZones.mo
This configuration does not cause any issue, hence the warning can be removed
=> Configure sensor to avoid warning

Buildings/ThermalZones/EnergyPlus/BaseClasses/Synchronize/ObjectSynchronizer.mo, Buildings/ThermalZones/EnergyPlus/Building.mo
This patch hides the results of the Spawn object synchronization as this is of no interest to users.
=> Hide results of synchronization

Buildings/ThermalZones/EnergyPlus/Examples/SmallOffice/ASHRAE2006Winter.mo, Buildings/ThermalZones/EnergyPlus/Examples/SmallOffice/Guideline36Winter.mo
This avoids the warning 'Access to component cor not recommended, it is not present in constraining type of declaration' in OCT.
=> Added constrained by clause

Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_7_to_8.0.0.mos
The parameter needed to be changed even if moved to the Obsolete package. This works with tests of Buildings.Examples
=> Corrected conversion script

Buildings/Resources/src/fluid/heatpumps/calibration/PythonModel/refrigerants.py, Buildings/package.mo, README.md
This is a bug fix in the refrigerant derivative in the python code.
It also changes the release date.
=> Maint 7.0.x release notes

Buildings/Resources/src/fluid/heatpumps/calibration/PythonModel/refrigerants.py, Buildings/package.mo, README.md
This is a bug fix in the refrigerant derivative in the python code from IBPSA, issue 1490.
It also changes the release date.
=> Patch release date

Buildings/Air/Systems/SingleZone/VAV/BaseClasses/ControllerChillerDXHeatingEconomizer.mo, Buildings/Controls/OBC/ASHRAE/G36_PR1/Generic/SetPoints/GroupStatus.mo, Buildings/Controls/OBC/CDL/Interfaces/BooleanInput.mo, Buildings/Controls/OBC/CDL/Interfaces/BooleanOutput.mo, Buildings/Controls/OBC/CDL/Interfaces/DayTypeInput.mo, Buildings/Controls/OBC/CDL/Interfaces/DayTypeOutput.mo, Buildings/Controls/OBC/CDL/Interfaces/IntegerInput.mo, Buildings/Controls/OBC/CDL/Interfaces/IntegerOutput.mo, Buildings/Controls/OBC/CDL/Interfaces/RealInput.mo, Buildings/Controls/OBC/CDL/Interfaces/RealOutput.mo, Buildings/Controls/OBC/CDL/Logical/MultiAnd.mo, Buildings/Controls/OBC/CDL/Logical/MultiOr.mo, Buildings/Controls/OBC/CDL/Logical/Validation/MultiAnd.mo, Buildings/Controls/OBC/CDL/Logical/Validation/MultiOr.mo, Buildings/Experimental/DHC/EnergyTransferStations/Combined/Generation5/Controls/SideHot.mo, Buildings/Resources/Scripts/Dymola/ConvertBuildings_from_8_to_9.0.0.mos, Buildings/package.mo
=> Renamed parameter in MultiAnd and MultiOr

Buildings/Experimental/DHC/CentralPlants/BaseClasses/PartialPlant.mo
This PR added additional modification based on https://github.com/lbl-srg/modelica-buildings/pull/2643#discussion_r716287583, which unified Boolean flag names of fluid ports to keep consistent with the naming convention.
=> unified boolean flag names

Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus.so, Buildings/Resources/Library/win64/ModelicaBuildingsEnergyPlus.dll, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/SpawnUtil.c
Correct segmentation fault if logging is set to debug and variable in E+ does not specify a unit.
This is also addressed on `issue2759_spawn_PATH` for the master.
Todo:
=> Correct segmentation fault during debug logging (maint 8.0.x)

Buildings/Resources/C-Sources/cryptographicsHash.c
The default prototype for ModelicaAllocateString will be int32, which
does not fit a whole pointer causing crashes in models using the
function.
Note: This should probably be ported to maintenance branches as well. It was reported in https://github.com/OpenModelica/OpenModelica/issues/8219
=> Include ModelicaUtilities.h for crypto hash

.travis.yml, bin/runUnitTests.py
This updates the BuildingsPy version, and enables by default colored output when running the regression tests.
=> Updated BuildingsPy to use colored output

.github/workflows/formatting.yml, .travis.yml
This updates BuildingsPy to a version that avoids waiting for user input if old reference files do not exist and the tests are run in batch mode.
=> Updated BuildingsPy version

Buildings/Utilities/IO/Python_3_8/UsersGuide.mo
Using backward slashes gives warnings when opening the library in OMEdit
=> Patched backward slashes in user guide

Buildings/HeatTransfer/Convection/Exterior.mo, Buildings/HeatTransfer/Convection/Interior.mo, Buildings/HeatTransfer/Data/OpaqueSurfaces.mo, Buildings/HeatTransfer/Windows/BaseClasses/InteriorConvection.mo, Buildings/ThermalZones/Detailed/BaseClasses/PartialParameterConstruction.mo, Buildings/ThermalZones/Detailed/BaseClasses/RoomHeatMassBalance.mo, Buildings/ThermalZones/Detailed/BaseClasses/SolarRadiationExchange.mo, Buildings/ThermalZones/Detailed/Constructions/BaseClasses/PartialConstruction.mo
This closes #2889.
The changes are to protected or final parameters, and to a base class for solar radiation exchange that is only meaningful within the thermal zone model. Hence, the conversion script is not updated.
=> Renamed parameters for #2889

Buildings/Resources/Library/linux64/libModelicaBuildingsEnergyPlus.so, Buildings/Resources/Library/win64/ModelicaBuildingsEnergyPlus.dll, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/BuildingInstantiate.c
This improves logging messages for searching the `PATH` and `SPAWNPATH` for the spawn executable.
(It only applies for the master as 8.1.0 does not implement this search.)
=> Patch spawn search debug message

.travis.yml, Buildings/Resources/C-Sources/cfdExchangeData.c, Buildings/Resources/C-Sources/cfdSendStopCommand.c, Buildings/Resources/C-Sources/cfdStartCosimulation.c, Buildings/Resources/C-Sources/cfdcosim.c, Buildings/Resources/C-Sources/exchangeValues.c, Buildings/Resources/C-Sources/fileWriterFree.c, Buildings/Resources/C-Sources/fileWriterInit.c, Buildings/Resources/C-Sources/fileWriterStructure.c, Buildings/Resources/C-Sources/getTimeSpan.c, Buildings/Resources/C-Sources/initArray.c, Buildings/Resources/C-Sources/jsonWriterInit.c, Buildings/Resources/C-Sources/plotFree.c, Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/C-Sources/plotSendString.c, Buildings/Resources/C-Sources/plotSendTerminalString.c, Buildings/Resources/C-Sources/pythonWrapper.c, Buildings/Resources/Library/win64/ModelicaBuildingsEnergyPlus.dll, Buildings/Resources/Scripts/BuildingsPy/conf.json, Buildings/Resources/Scripts/travis/optimica/jm_ipython.sh, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/SpawnFMU.c, Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/SpawnUtil.h, Buildings/ThermalZones/EnergyPlus/BaseClasses/package.mo, Buildings/ThermalZones/EnergyPlus/BaseClasses/package.order, Buildings/package.mo
This is based on `maint_8.1.x_IBPSASync_issue1594_headerFiles`.
This enables simulation of Spawn also for OpenModelica on Windows.
This avoids errors such as 
```
[json.exception.parse_error.101] parse error at line 4, column 16: syntax error while parsing value-invalid string: forbidden character after backslash; last read: ‘“C:\U’”
```
on Windows. See also https://github.com/lbl-srg/modelica-buildings/issues/2924#issue-1172246345
=> Maint 8.1.x - correct backward slashes for Spawn if used with OpenModelica on Windows

.github/workflows/formatting.yml, .travis.yml
This avoids issues on travis as the import sometimes fails with an error due to the headless setup
=> Updated BuildingsPy to version that does not import matplotlib.pyplot

Buildings/Experimental/DHC/Networks/BaseClasses/PartialConnection2Pipe2Medium.mo, Buildings/Experimental/DHC/Networks/BaseClasses/PartialDistribution2Pipe2Medium.mo, Buildings/Experimental/DHC/Plants/Steam/SingleBoiler.mo
@dhblum @khinkelman : This allows `Buildings.Experimental.DHC.Plants.Steam.Examples.SingleBoiler` to compile in OpenModelica.
Note that the `constrainedby` clause was missing. Without it, the parameter assignments are not preserved (some tools preserve the medium assignment, but it is not required without the `constrainedby` clause).
Simulation fails with `division by zero at time 0, (a=0) / (b=0), where divisor b expression is: 0.0`. I think this is an open issue in OpenModelica as we have other fluid models with this behavior.
I also changed the expansion vessel pressure assignment from `p` to `p_start`, as `p` turns out to be not used and will be removed.
@dhblum : Please go ahead and merge it to your development branch if you agree with the changes, and delete this branch …
=> Issue2905 steam dhs full sys patch single boiler

Buildings/ThermalZones/EnergyPlus_9_6_0/UsersGuide.mo
This clarifies that in EnergyPlus, a year always has 365 days.
=> Added documentation about leap year

Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash2501.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash3001.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash3501.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash4001.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash5001.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash6001.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX400.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX500.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX600.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX725.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX850.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash0400.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash0500.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash0650.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash0800.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash1000.mo, Buildings/package.mo
This ensures that if a record is dragged in a GUI, it will be declared as a parameter
=> Add defaultComponentName and defaultComponentPrefixes

Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash2501.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash3001.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash3501.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash4001.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash5001.mo, Buildings/Fluid/Boilers/Data/Lochinvar/Crest/FBdash6001.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX400.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX500.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX600.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX725.mo, Buildings/Fluid/Boilers/Data/Lochinvar/FTXL/FTX850.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash0400.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash0500.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash0650.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash0800.mo, Buildings/Fluid/Boilers/Data/Lochinvar/KnightXL/KBXdash1000.mo, Buildings/package.mo
This adds `defaultComponentPrefixes = "parameter"` to the maintenance branch.
It contains https://github.com/lbl-srg/modelica-buildings/pull/3011
=> Maint 8.1.x patch default component prefix boiler

Buildings/Fluid/HeatExchangers/DryCoilCounterFlow.mo
This only affects the special case of nEle=1. Results are not affected by this change.
=> Patch to avoid division by zero if nEle=1

Buildings/Resources/src/ThermalZones/install.py
Note: `shell=True` could probably be changed to `False` since no shell interpretation should be needed anymore. I created a minimal fix instead.
```
modelica-buildings$ cp -a Buildings/ Buildings\ blabla
modelica-buildings$ Buildings\ blabla/Resources/src/ThermalZones/install.py
/bin/sh: 1: /home/marsj/modelica-buildings/Buildings: Permission denied
```
Should probably also be fixed for 9.x maintenance
=> Handle spaces in paths when installing Spawn

.github/workflows/formatting.yml
This removes deprecated version (https://github.com/lbl-srg/modelica-buildings/actions/runs/3605039255) and git-lfs
=> Updated set up of github actions

Buildings/Fluid/Sensors/BaseClasses/PartialDynamicFlowSensor.mo, Buildings/HeatTransfer/Data/BaseClasses.mo
This is for #1671. It avoids comparing a real-valued parameter for equality which is not permitted by the Modelica Language Standard
=> Corrected annotation (maint 9.1.x)

Buildings/Fluid/FixedResistances/CheckValve.mo, bin/verifyFiles.py
The graphical primitive Line has no attribute lineThickness. It is instead call thickness
=> Corrected graphical annotation

Buildings/Resources/Scripts/BuildingsPy/conf.yml
This adds Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel to the list of models simulated with OCT. It works locally and in Modelon's CI tests.
=> Added Plants.Cooling.Examples.ElectricChillerParallel

Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilWetRegime.mo
This sets the start value for NTUAirSta which avoids a division by zero in OpenModelica.
=> Merged IBPSA WetCoilWetRegime

Buildings/Fluid/HeatExchangers/BaseClasses/WetCoilWetRegime.mo
This sets the start value for NTUAirSta which avoids a division by zero in OpenModelica.
=> Merged IBPSA WetCoilWetRegime (maint 9.1.x)

Buildings/Fluid/Sources/Outside_CpLowRise.mo
This merges a change from IBPSA that removes an annotation that uses a variable that does no longer exist
=> Removed invalid annotation in Outside_CpLowRise

Buildings/Fluid/Sources/Outside_CpLowRise.mo
This merges a change from IBPSA that removes an annotation that uses a variable that does no longer exist
=> Removed invalid annotation in Outside_CpLowRise (maint 9.1.x)

Buildings/Resources/C-Sources/exchangeValues.c, Buildings/Resources/C-Sources/fileWriterFree.c, Buildings/Resources/C-Sources/fileWriterStructure.c, Buildings/Resources/C-Sources/getTimeSpan.c, Buildings/Resources/C-Sources/initArray.c, Buildings/Resources/C-Sources/jsonWriterInit.c, Buildings/Resources/C-Sources/plotInit.c, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/SpawnFMU.c, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/SpawnUtil.c, Buildings/Resources/src/ThermalZones/EnergyPlus_9_6_0/C-Sources/cryptographicsHash.c
Numerous examples fail to compile with the OpenModelica C++ runtime for this reason, see
https://libraries.openmodelica.org/branches/cpp/Buildings_latest/Buildings_latest.html
So far some allocations do cast, some don't. It would be good if all did.
This is required if compiled with C++ to avoid errors like:
```
In file included from ./OMCppBuildings_latest_Buildings.BoundaryConditions.WeatherData.Examples.ReaderTMY3Functions.cpp:7:
Buildings 10.0.0-master/Resources/C-Sources/getTimeSpan.c:27:9: error: cannot initialize a variable of type 'char *' with an rvalue of type 'void *'
char *result = malloc(len1 + len2 + 1);
^        ~~~~~~~~~~~~~~~~~~~~~~~
```
or
```
In file included from ./OMCppBuildings_latest_Buildings.Utilities.Plotters.Examples.ScatterFunctions.cpp:8:
Buildings …
```
=> Add type casts to malloc and realloc in C-Sources

Buildings/Fluid/Boilers/BaseClasses/PartialBoiler.mo, Buildings/Fluid/Delays/DelayFirstOrder.mo, Buildings/Fluid/HydronicConfigurations/UsersGuide.mo, Buildings/package.mo
This closes #3391.
Marked as draft for now for the following item:
=> Issue3391 documentation and release notes

Buildings/Experimental/DHC/Plants/Reservoir/BoreField.mo
Removed final keyword in bore field data record.
This allows the record to be reassigned by models that extend from this model.
=> Maint 9.1.x bore field final

Buildings/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/finiteLineSource_Equivalent.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/finiteLineSource_Integrand_Equivalent.mo, Buildings/Fluid/HydronicConfigurations/ActiveNetworks/Examples/BaseClasses/LoadThreeWayValveControl.mo, Buildings/Fluid/HydronicConfigurations/ActiveNetworks/Examples/BaseClasses/LoadTwoWayValveControl.mo, Buildings/Fluid/HydronicConfigurations/ActiveNetworks/Examples/BaseClasses/PartialLoadValveControl.mo, Buildings/Fluid/HydronicConfigurations/ActiveNetworks/Examples/DecouplingMixing.mo, Buildings/Fluid/HydronicConfigurations/ActiveNetworks/Examples/InjectionTwoWayConstantReturn.mo, Buildings/Fluid/HydronicConfigurations/ActiveNetworks/Examples/InjectionTwoWayVariable.mo, Buildings/Fluid/HydronicConfigurations/Controls/PIDWithOperatingMode.mo, Buildings/Obsolete/Fluid/Movers/Data/Pumps/Wilo/Stratos25slash1to4.mo, Buildings/Obsolete/Fluid/Movers/Data/Pumps/Wilo/Stratos32slash1to12.mo
This closes #3416.
@mwetter -
It looks like most of them are just links not properly updated after the classes were moved around.
The two exceptions are `Buildings.Fluid.HydronicConfigurations.Controls.OperatingModes.enabled` and `Buildings.Fluid.HydronicConfigurations.Controls.OperatingModes.heating` in `HydronicConfigurations.Controls.PIDWithOperatingMode`. They point to constants instead of classes and therefore cannot be clicked to open in Dymola. Because the package `OperatingModes` which contains these constants is already linked uptext in the documentation, I simply replaced these two links with just plain texts.
I will go ahead and merge relevant changes to IBPSA.
=> Issue3416 correct broken links

Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/convectionResistanceCircularPipe.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/partialInternalResistances.mo
This integrates IBPSA 1762.
This corrects the variability as assigning an input to a parameter is not allowed
=> Corrected variability

Buildings/HeatTransfer/Data/BaseClasses.mo
This avoids a test for equality in the icon, which is not compliant with the Modelica Language Standard. It also improves the icon layout and sets the displayUnit for density.
This fix avoids a warning in OMEdit.
=> Corrected annotation in HeatTransfer data

Buildings/HeatTransfer/Data/BaseClasses.mo
This avoids a test for equality in the icon, which is not compliant with the Modelica Language Standard. It also improves the icon layout and sets the displayUnit for density.
This fix avoids a warning in OMEdit.
=> Corrected annotation in HeatTransfer data (maint 9.1.x)

Buildings/Fluid/Chillers/BaseClasses/PartialElectric.mo, Buildings/Fluid/Chillers/Data/ElectricEIR.mo, Buildings/Fluid/Chillers/Data/ElectricReformulatedEIR.mo, Buildings/Fluid/Chillers/ElectricEIR.mo, Buildings/Fluid/Chillers/ElectricReformulatedEIR.mo
This PR provides sources (i.e. [EnergyPlus Engineering Reference](https://energyplus.net/assets/nrel_custom/pdfs/pdfs_v22.1.0/EngineeringReference.pdf)) and details in the documentation for electric chillers.
This closes #3425.
=> Issue3425 documentation chiller EIR factors

Buildings/Experimental/DHC/Plants/Cooling/Controls/ChilledWaterPumpSpeed.mo, Buildings/package.mo
=> Issue3470 restrict to two pumps

.travis.yml, Buildings/Resources/Scripts/BuildingsPy/conf.yml
This adds the directory to the tests, and excludes models that don't translate with OpenModelica
=> Add Buildings.Templates to OpenModelica tests

Buildings/Occupants/BaseClasses/binaryVariableGeneration.mo, Buildings/Occupants/BaseClasses/exponentialVariableGeneration.mo, Buildings/Occupants/BaseClasses/linear1D.mo, Buildings/Occupants/BaseClasses/logit1D.mo, Buildings/Occupants/BaseClasses/logit1DQuadratic.mo, Buildings/Occupants/BaseClasses/logit2D.mo, Buildings/Occupants/BaseClasses/weibull1DOFF.mo, Buildings/Occupants/BaseClasses/weibull1DON.mo, Buildings/Occupants/BaseClasses/weibullVariableGeneration.mo
=> Added missing seed, added icon

Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/InternalResistancesOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/InternalResistancesOneUTubeNegative.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/InternalResistancesTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/InternalResistancesTwoUTubeNegative.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesTwoUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/partialInternalResistances.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalHEXOneUTube.mo, Buildings/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/InternalHEXTwoUTube.mo
This integrates IBPSA, issue 1814. The use of this function is not allowed inside other functions, and causes OpenModelica to fail during translation
=> Corrected wrong use of getInstanceName

Buildings/Controls/OBC/Utilities/PIDWithAutotuning/FirstOrderAMIGO.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/Relay/Controller.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/BaseClasses/Gain.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/BaseClasses/Validation/Gain.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/ControlProcessModel.mo, Buildings/Controls/OBC/Utilities/PIDWithAutotuning/SystemIdentification/FirstOrderTimedelayed/Validation/ControlProcessModel.mo, Buildings/Resources/Scripts/Dymola/Controls/OBC/Utilities/PIDWithAutotuning/Relay/Validation/Controller.mos, Buildings/Resources/Scripts/OpenModelica/compareVars/Buildings.Controls.OBC.Utilities.PIDWithAutotuning.Relay.Validation.Controller.mos
@JayHuLBL Please take a look at the PR based on your comments.
=> Issue2884 pid autotuning

Buildings/Experimental/DHC/EnergyTransferStations/Heating/Direct.mo, Buildings/Experimental/DHC/EnergyTransferStations/Heating/Indirect.mo, Buildings/Experimental/DHC/Examples/Combined/BaseClasses/BoreField.mo, Buildings/Experimental/DHC/Examples/Combined/BaseClasses/PartialSeries.mo, Buildings/Experimental/DHC/Examples/Combined/BaseClasses/package.order, Buildings/Experimental/DHC/Plants/Heating/package.mo, Buildings/Experimental/DHC/Plants/Reservoir/package.mo, Buildings/Experimental/DHC/Plants/Reservoir/package.order, Buildings/Experimental/DHC/Plants/package.order, Buildings/Resources/Scripts/Conversion/ConvertBuildings_from_10_to_11.0.0.mos, Buildings/package.mo
This is for https://github.com/lbl-srg/modelica-buildings/issues/3628 and implements relatively minor clean up.
=> Issue3628 clean dhc

Buildings/ThermalZones/EnergyPlus_9_6_0/UsersGuide.mo
The documentation was not been updated to reflect an enhancement to Spawn's warmup procedure. Specifically, a change was made to use wall temperatures instead of air temperature to exit warmup iteration.
https://github.com/NREL/Spawn/commit/ef91931157c988478c0ce212a8a0e708ce7e8035
close #3176
=> Update documentation about Spawn's warmup procedure

Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/CoolingOnly/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/DualDuctColdDuctMin/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/DualDuctMixConDischargeSensor/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/DualDuctMixConInletSensor/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/DualDuctSnapActing/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/ParallelFanCVF/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/ParallelFanVVF/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/Reheat/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/SeriesFanCVF/Subsequences/Alarms.mo, Buildings/Controls/OBC/ASHRAE/G36/TerminalUnits/SeriesFanVVF/Subsequences/Alarms.mo, Buildings/package.mo
This corrects a typo in the documentation.
=> Corrected typo (maint_10.0.x)

Buildings/Airflow/Multizone/MediumColumn.mo, Buildings/Airflow/Multizone/MediumColumnDynamic.mo, Buildings/BoundaryConditions/SolarIrradiation/BaseClasses/SkyClearness.mo, Buildings/Controls/OBC/CDL/Types/ZeroTime.mo, Buildings/Controls/SetPoints/SupplyReturnTemperatureReset.mo, Buildings/Fluid/Sources/BaseClasses/Outside.mo, Buildings/Fluid/Sources/BaseClasses/PartialSource_Xi_C.mo, Buildings/Fluid/Sources/Boundary_pT.mo, Buildings/Fluid/Sources/Boundary_ph.mo, Buildings/Fluid/Sources/MassFlowSource_T.mo, Buildings/Fluid/Sources/MassFlowSource_WeatherData.mo, Buildings/Fluid/Sources/MassFlowSource_h.mo, Buildings/Fluid/Sources/TraceSubstancesFlowSource.mo, Buildings/Utilities/Psychrometrics/BaseClasses/HumidityRatioVaporPressure.mo, Buildings/Utilities/Time/CalendarTime.mo, Buildings/Utilities/Time/Types/ZeroTime.mo
This merges updates from IBPSA that corrects `HideResult` annotation, `displayUnit` annotation, and extends the time covered by `CalendarTime`.
=> Merged IBPSA, issues 1842, 1847, 1850

Buildings/Airflow/Multizone/MediumColumn.mo, Buildings/Airflow/Multizone/MediumColumnDynamic.mo, Buildings/Controls/OBC/CDL/Types/ZeroTime.mo, Buildings/Controls/SetPoints/SupplyReturnTemperatureReset.mo, Buildings/Fluid/Sources/BaseClasses/Outside.mo, Buildings/Fluid/Sources/BaseClasses/PartialSource_Xi_C.mo, Buildings/Fluid/Sources/Boundary_pT.mo, Buildings/Fluid/Sources/Boundary_ph.mo, Buildings/Fluid/Sources/MassFlowSource_T.mo, Buildings/Fluid/Sources/MassFlowSource_WeatherData.mo, Buildings/Fluid/Sources/MassFlowSource_h.mo, Buildings/Fluid/Sources/TraceSubstancesFlowSource.mo, Buildings/Utilities/Psychrometrics/BaseClasses/HumidityRatioVaporPressure.mo, Buildings/Utilities/Time/CalendarTime.mo, Buildings/Utilities/Time/Types/ZeroTime.mo, bin/verifyFiles.py
This merges updates from IBPSA that corrects `HideResult` annotation, `displayUnit` annotation, and extends the time covered by `CalendarTime`.
=> Merges IBPSA, issues 1842, 1847, 1850 (maint_9.1.x)

Buildings/Air/Systems/SingleZone/VAV/ChillerDXHeatingEconomizer.mo
This corrects the wrong dimension, which OMEdit detects and triggers a warning
=> Corrected wrong parameter assignment in ChillerDXHeatingEconomizer (maint 10.0.x)

Buildings/Air/Systems/SingleZone/VAV/ChillerDXHeatingEconomizer.mo
This corrects the wrong dimension, which OMEdit detects and triggers a warning
=> Corrected wrong parameter assignment in ChillerDXHeatingEconomizer

Buildings/Resources/C-Sources/EnergyPlus_9_6_0_Wrapper.c, Buildings/ThermalZones/EnergyPlus_9_6_0/Actuator.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/BaseClasses/ThermalZoneAdapter.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/BaseClasses/exchange.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/OpaqueConstruction.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/OutputVariable.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/Schedule.mo, Buildings/ThermalZones/EnergyPlus_9_6_0/ZoneSurface.mo
This is no longer needed. In the compiled C library, the argument is still present, but can be removed next time when the libraries need to be recompiled.
=> Removed argument initialCall in Spawn

Buildings/Air/Systems/SingleZone/VAV/ChillerDXHeatingEconomizer.mo
This corrects the wrong dimension, which OMEdit detects and triggers a warning
=> Corrected wrong parameter assignment in ChillerDXHeatingEconomizer (maint_9.1.x)

Buildings/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowAIT.mo
This PR reduces the interval time in the model `Buildings.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowAIT` in order to reduce the simulation warnings and to speed-up the simulation during the initial phases. This should prevent the CI to fail.
More details are available in https://github.com/OpenModelica/OpenModelica/issues/11000
=> Interval time reduced in order to speed-up the simulation during the initial phase

Buildings/Fluid/DXSystems/Cooling/AirSource/Data/Generic/BaseClasses/PerformanceCurve.mo, Buildings/Fluid/DXSystems/Cooling/AirSource/Data/Generic/DXCoil.mo, Buildings/Fluid/DXSystems/Cooling/WaterSource/Data/Generic/BaseClasses/PerformanceCurve.mo, Buildings/Fluid/DXSystems/Cooling/WaterSource/Data/Generic/DXCoil.mo, Buildings/Fluid/DXSystems/Heating/AirSource/Data/Generic/DXCoil.mo
@mwetter I have replaced the unused variable names from the documentation sections with the correct parameter pairs. I also checked to make sure there weren't any other unused parameters in the documentation. Please review this when you get a chance. Thanks!
=> Issue3733 dx coil cleanup

Buildings/Fluid/AirFilters/BaseClasses/FiltrationEfficiency.mo, Buildings/Fluid/AirFilters/BaseClasses/FlowCoefficientCorrection.mo, Buildings/Fluid/AirFilters/BaseClasses/MassAccumulation.mo, Buildings/Fluid/AirFilters/BaseClasses/MassTransfer.mo, Buildings/Fluid/AirFilters/BaseClasses/PressureDropWithVaryingFlowCoefficient.mo, Buildings/Fluid/AirFilters/BaseClasses/Validation/FiltrationEfficiency.mo, Buildings/Fluid/AirFilters/BaseClasses/Validation/MassAccumulation.mo, Buildings/Fluid/AirFilters/BaseClasses/Validation/MassTransfer.mo, Buildings/Fluid/AirFilters/Empirical.mo, Buildings/Fluid/AirFilters/Examples/Empirical.mo
This is to address the [comments](https://github.com/lbl-srg/modelica-buildings/pull/3676#issuecomment-2048609110).
=> Issue3618 air filter

Buildings/Controls/OBC/Utilities/Validation/OptimalStartCoolingNegativeStartTime.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartCoolingPositiveStartTime.mo, Buildings/Controls/OBC/Utilities/Validation/OptimalStartHeating.mo, Buildings/Resources/Scripts/Dymola/Controls/OBC/Utilities/Validation/OptimalStartCoolingNegativeStartTime.mos, Buildings/Resources/Scripts/Dymola/Controls/OBC/Utilities/Validation/OptimalStartCoolingPositiveStartTime.mos, Buildings/Resources/Scripts/Dymola/Controls/OBC/Utilities/Validation/OptimalStartHeating.mos
This is for #3865, pending external tests.
This PR reduces the tolerance of `Buildings.Controls.OBC.Utilities.Validation{OptimalStartCoolingNegativeStartTime,OptimalStartCoolingPositiveStartTime,OptimalStartHeating}` by a factor of 10 in both the `.mo` file annotations and the `.mos` files.
This did _not_ cause the unit test results to change.
=> issue 3865 change OptimalStart test tolerance 

Buildings/Resources/C-Sources/cfdSendStopCommand.c
If multiple simulations are performed for a model that includes FFD without fully releasing the library, then the second simulation would fail due to that the global structure "cosim" has not been set to NULL in the destructor. The use case can be for instance when the model is compiled into an FMU and the following is performed:
1. Load the FMU 
2. Simulate
3. Use the FMI reset method
4. Simulate again (will fail)
An example model is Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection)
Setting the structure "cosim" to NULL will resolve the issue.
=> Fixed issue when multiple sims are performed for models including FFD

Buildings/DHC/Loads/BaseClasses/Validation/BaseClasses/FanCoil2PipeHeatingValve.mo
This corrects an annotation that used a non-existent variable
=> Corrected wrong annotation in FanCoil2PipeHeatingValve

Buildings/Experimental/DHC/Loads/BaseClasses/Validation/BaseClasses/FanCoil2PipeHeatingValve.mo
This corrects an annotation that used a non-existent variable
=> maint 10.x: Corrected wrong annotation in FanCoil2PipeHeatingValve

Buildings/Controls/OBC/Utilities/OptimalStart.mo
This corrects a typo in the documentation.
=> Correct typo in documentation of OptimalStart.mo

Buildings/Fluid/Geothermal/ZonedBorefields/BaseClasses/HeatTransfer/GroundTemperatureResponse.mo
this fixes OpenModelica Issue #12677
=> kappa calculation moved from initial equation to binding equation

Buildings/Electrical/BaseClasses/WindTurbine/PartialWindTurbine.mo
This corrects a link in the revision notes for the wind turbine base class.
=> Correct link in revision notes

Buildings/Resources/src/fmi-library/CMakeLists.txt
This PR includes changes to the build system to instead use the latest FMILibrary (FMIL) released yesterday.
Let me know if anything else is needed, any tests or similar? For now I have only verified that the build command that was in the top of the file works, that is:
```
rm -rf build && mkdir build && cd build && cmake .. && cmake --build . && cd ..
```
End of build output:
```
...
100% tests passed, 0 tests failed out of 65
Label Time Summary:
skip_memcheck    =   0.01 sec*proc (1 test)
Total Test time (real) =   2.05 sec
[ 77%] Completed 'fmi-library-modelon'
Copying to Modelica library directory '/opt/modelica-buildings/Buildings/Resources/src/fmi-library/../../Library/linux64/'
Deleting /opt/modelica-buildings/Buildings/Resources/src/fmi-library/../../Library/linux64//libfmilib.a …
```
=> Update FMI Library to version 3.0, up from 2.2

Buildings/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/Validation/FiniteLineSource_Integrand_Length.mo
This merges IBPSA, issue2051_FiniteLineSource_Integrand_Length, and ensures that the results are the same for MSL 4.0 and 4.1
=> Changed value of small
